### ISSUE TITLE
Update photomap addition to /v2/photomap.add

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#103]
All of the Photomap calls are now in the /v2/ API, with the last one to be completed that you are using, addphoto.xml available as the new /v2/photomap.add call:

http://www.cyclestreets.net/api/v2/photomap.add/

This should be pretty easy to migrate to, as the submission side is all the same - you just need to get the response interpreted in its new JSON format rather than the grotty old XML.

**Comment by oliverlockwood** [comment]
We've already done this 😄 

See https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/V2Api.java#L72-L83

@mvl22 if you're happy this issue doesn't cover anything else, then shall we close it?
