### ISSUE TITLE
LiveRide does not mute other audio

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/android#104]
When LiveRide is giving instructions then the audio should be focused with something like [requestAudioFocus](http://developer.android.com/reference/android/media/AudioManager.html#requestAudioFocus%28android.media.AudioManager.OnAudioFocusChangeListener,%20int,%20int%29).

Thanks

**Comment by oliverlockwood** [comment]
Some links that might be useful:
-  https://stackoverflow.com/questions/27119866/android-texttospeech-override-other-sounds
-  https://developer.android.com/guide/topics/media-apps/volume-and-earphones
-  https://developer.android.com/reference/android/media/AudioManager#AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK
-  https://gist.github.com/LukasKnuth/0c0d17b343483d25aca2
