### ISSUE TITLE
Fail to find route results in loss of waypoints

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/android#105]
On a train I set a couple of waypoints and then planned a route just as we went into a tunnel.

Route finding failed and my waypoints disappeared. I had the fiddly job of setting them up again - what I was missing was a 'retry' option.

**Comment by mvl22** [comment]
Possibly related to #106.

**Comment by oliverlockwood** [comment]
Note to self: investigate this as part of #186

**Comment by oliverlockwood** [comment]
@si-the-pie this no longer reproduces as far as I can tell - see e.g. your own experiences with #298.

I'm going to close this; please feel free to reopen if you disagree.
