### ISSUE TITLE
LiveRide replan loses intermediate waypoints

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#106]
Bug report from a user:

> If LiveRide replans the journey because you are too far away, it disregards the intermediate waypoints and recalculates to the last waypoint. This is frustrating.

This definitely seems high priority to fix.

**Comment by jf1** [comment]
It's one of the reasons I rarely use the LiveRide feature, so +1 for it being a high priority (along with using vector tiles so the map can auto-rotate #110 #155)

**Comment by oliverlockwood** [comment]
I'll try and take this on *after* we've cut a release (#255).
