### ISSUE TITLE
Upgrade Mapsforge library to 0.6 to improve pinch zoom

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#115]
https://github.com/mapsforge/mapsforge/releases

now has 0.6, which seems to have improved all kinds of things, in particular pinch zoom (which is rather unnatural at present, and much poorer than other mapping applications).

This would be good quick win to improve, if integration is easy.

**Comment by jezhiggins** [comment]
This isn't relevant to the way we use Mapsforge.  We use OsmDroid as our mapping toolkit, so all the zoom, pan, etc, is handled by that.  We integrate Mapsforge with OsmDroid by implementing a custom tile provider, using Mapsforge to generate maps tiles on the fly. 

We should probably move to a later version of Mapsforge - we're currently on 0.3.0 - but that would require additional work to the map compilation pipeline, and possibly also our render pipeline.
