### ISSUE TITLE
Add support for Android 6.0

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#116]
Bug report from a user:

> Since upgrading my rom to Marshmallow 6.0.1 from Lollipop the app no longer works. It crashes upon launch. I've tried an uninstall and then reinstalling from the Play store, but still encounter the same problem. I have a Galaxy S4 using a custom rom by Mokee. All other apps still work as well since the upgrade. Thanks.

**Comment by jfmchivall** [comment]
Might this be the same bug as #118 ?

**Comment by jezhiggins** [comment]
I think it might be the same as #118, yes.  Let's move the discussion over there.
