### ISSUE TITLE
LiveRide broken on some Android phones

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#126]
High priority bug report:

> LiveRide on Android no longer seems to do anything, other than display the map with a line on it (thanks for fixing the non-display of the map). It doesn't say anything and there is no display of the next turn.

Direct message me if you want the user's details - their excellent record of feedback means they are likely to be willing to give more info or test things.

Also a similar report:

> Since the last android update I no longer get voice directions. I have untucked the 'silence when pebble' but that made no difference either

And another:

> Hi, I have a HTC Desire 620 running Android v4.4.4 and am unable to get the Liveride turn by turn audio directions to work. The display works fine with written instructions and location on map both ok, however the audible instructions are nonexistent. 
> I have tried reinstalling the app and updating the phone software to no avail.
> I have used this function on an older phone several years ago and thought it was great, any assistance in making it work again would be most appreciated, as this is my app of choice for route finding.

And another:

> App is navigating but unable to get the turn by turn voice instructions to work. Mobile data / GPS / Bluetooth all on and working (with Google maps).

I've tried on my Samsung S3 and it works fine for me.

**Comment by mvl22** [comment]
Actually it seems I had the 3.2 release on my S3. Having just upgraded, I can reproduce the problem.

**Comment by colcord** [comment]
Hi, just found your github account. I've sent an email with a bug report, and left comment in Play store. I have a Nexus 6P, and have not been able to get voice navigation to work since April update. Happy to help troubleshoot. I've tried restarting Nexus 6P. I've tried switching TTS from SVOX back to Google.

**Comment by jezhiggins** [comment]
It's a cock-up in the logic when we extended the Pebble support.  Speech was off if you didn't have a Pebble watch, which is obviously unhelpful.  That's now corrected.

**Comment by colcord** [comment]
Hi working fine now. Thanks for the prompt action.
