### ISSUE TITLE
Upgrading osmdroid dependency to 5.x

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#133]
This issue is to track upgrading the `osmdroid` dependency, which I've started looking at.

There's quite a lot of changes after 4.3, so my thought was to work through iteratively by first upgrading to 5.0.1, resolving issues, and then moving on to 5.1 and 5.2.  From experimentation:

#### Upgrading to 5.0.1
In this version, the main non-backward-compatible change that affects us at compile time appears to be the removal of the `org.osmdroid.http` package, which was done in [this commit](https://github.com/osmdroid/osmdroid/commit/7f6191f57593f46fd5a903c6fe7d86aadf6d7db2).  From the commit message, it appears to be a desire to move away from Apache HttpClient towards  UrlConnection.
I can see more than one option on how to proceed:
1.  Continue using Apache HttpClient and implement our own form of the `HttpClientFactory` classes that have been removed from `osmdroid`.
2.  Migrate our code that makes REST requests to use UrlConnection instead.

From reading around blogs, StackOverflow etc I don't think (1) is the way forward, as it seems that Google is not really supporting Apache HttpClient going forward.  Quote from http://android-developers.blogspot.co.uk/2011/09/androids-http-clients.html:
>Apache HTTP client has fewer bugs on Eclair and Froyo. It is the best choice for these releases.
>For Gingerbread and better, HttpURLConnection is the best choice.
>New applications should use HttpURLConnection; it is where we will be spending our energy going forward.

Since our minSdkVersion is already 14 (Ice Cream Sandwich) it seems to make sense for us to go down the UrlConnection route, but I'd be grateful for opinions from the maintainers. @jezhiggins @mvl22, what are your thoughts on the above - and, indeed, do you have any better ideas?

**Comment by oliverlockwood** [comment]
Adding to this, if we do move away from Apache HttpClient, we should probably do this across the board, even where we're not forced to be the deprecation of the osmdroid HttpClientFactory.  I imagine much of the complexity here will be around the `ApiClient` class due to the multipart entities it constructs.  Using the UrlConnection code natively may be a bit of a headache, so perhaps we should consider including a 3rd party library such as [Ion](https://github.com/koush/ion), [Loop4J](http://loopj.com/android-async-http/) or [Retrofit](https://square.github.io/retrofit/).  Any thoughts on that?

**Comment by oliverlockwood** [comment]
A further update - the Android community at Sky has come out reasonably strongly in favour of using Retrofit, so I'll probably spike in that direction unless I hear that you guys really don't want to for some reason.

**Comment by jezhiggins** [comment]
I don't have opinions on this in any particular direction, but at a first glance Retrofit does look pretty smooth and I certainly wouldn't object to it.

**Comment by mvl22** [comment]
If that is now the Google-recommended client, and works at minSdkVersion=14, then I'd say go for it.

**Comment by oliverlockwood** [comment]
@mvl22 @jezhiggins on the ongoing work I'm doing to move to Retrofit for the `ApiClient` calls, I've realised there was something missing from #134 on the `getPOIs()` calls.

Specifically, the functionality in [`ApiClient.callApi()`](https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.java#L340-347) which optionally calls `callApiWithCache()` instead of `callApiRaw()`, depending on whether an [`ApiCustomiser`](https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiCustomiser.java) has been provided which enables caching for that path.

I can't see any implementations of `ApiCustomiser` in the codebase, nor can I find any calls to `ApiClient.setCustomiser()`.  Is this functionality simply not used?

Note that:
-  when it comes on to migrating the APIs that use `callApiWithCache()` directly, I intend to implement caching using the mechanisms provided by Retrofit & OkHttp
-  I've raised #135 in the meantime which covers the other usages of `callApi()`; I believe this PR makes sense in its own right
-  the question I have for you guys is whether the additional complexity of this optional cache mechanism is required or not.  (If it is, I'll raise a separate PR to back-apply it to all the APIs migrated by #134 and #135.)

Looking forward to your thoughts.

**Comment by jezhiggins** [comment]
The ApiCustomiser isn't used within the CycleStreets app, but was used by (at least) one of the third-party branded apps that were built on the libraries.  There's no need to carry through in the work you're doing.  If those apps are migrated, I'll do whatever fiddling around needs doing then.

**Comment by mvl22** [comment]
@jezhiggins Which app was that?

If the Hackney app, am keen to maintain that codebase, specifically in terms of getting the GPS tracking facility into the main app.

**Comment by jezhiggins** [comment]
It was Cycle S&NS.  It's entirely unrelated to the tracking, which has already been pulled into a library of its own.

**Comment by oliverlockwood** [comment]
Reopening this issue to continue the discussion.  I'm looking at the upgrade to 5.2 (I've got as far as 5.1 already) and I'm trying to understand why we have our own copy of `MyLocationNewOverlay.java` (as opposed to using osmdroid's class of the same name).

From what I've looked at in the Git history, my educated guess is that it was to add extra functionality and/or fix bugs, but @jezhiggins / @mvl22 / anyone else can you help me out with the background on this one?  Ideally if we can I'd like to remove our copy of the class, to reduce complexity, but I'd hate to miss something crucial in doing that.

**Comment by jezhiggins** [comment]
Yep, that's pretty much it.  At the time we were looking at using larger tiles for higher resolution screens, and OsmDroid's location overlay didn't work properly so I pulled it out of the OsmDroid source and fixed it up.  Our own LocationOverlay inherits from it to provide the CycleStreets specific behaviour we want. 

If OsmDroid's overlay works, then use it and strip our version out.

**Comment by mvl22** [comment]
Report from a user trying the private builds:

`FYI the most recent version that doesn't crash on loading on a Samsung Galaxy s6 edge (android 6.0.1) is the following one: CycleStreets-vNext-2016-06-11-0043.apk`

(May not be related to the above work specifically, but perhaps another recent change.)

**Comment by oliverlockwood** [comment]
@mvl22 I'm hoping that once you get the chance to test, we'll be able to close this issue - over to you when you have the chance.

**Comment by mvl22** [comment]
I've tried the latest build on an S3 and not found any regressions - nice work.

Could you check whether the geolocation button for you? It doesn't seem to be giving me a fix.

**Comment by jf1** [comment]
I manually installed [this](http://www.jezuk.co.uk/cyclestreets/master/CycleStreets-vNext-2016-09-28-0044.apk) last week and have just confirmed geolocation working as expected on an S5

Is there any way to confirm I'm using that version?
About page still shows: net.cyclestreets/3.4

**Comment by oliverlockwood** [comment]
Good question @jf1, I'll take a look in the next day or two - I feel that the about page should probably include a build number as well as minor/major version.

**Comment by mvl22** [comment]
> I feel that the about page should probably include a build number as well as minor/major version.

Good idea.

Happy to push the build live if you are.

**Comment by oliverlockwood** [comment]
@jf1 As per #159, now fixed, from builds tonight and onwards the About page will include a build identifier (actually a timestamp of when the build was kicked off, such as the following):
<img width="279" alt="screen shot 2016-10-11 at 21 54 03" src="https://cloud.githubusercontent.com/assets/6017680/19288348/8b9b21d8-8ffd-11e6-83cf-7e6d6cbb600c.png">

@mvl22 I suggest holding off pushing a new build live to the Play Store until we fix #157 (which is on my list, unless someone beats me to it) - then the release can include not only underlying framework changes, but also a bug fix, which hopefully will make users happy 😃

**Comment by oliverlockwood** [comment]
Also @mvl22 using the latest build, manually installed on my phone, the location fix works fine for me too.

I am going to close this issue as resolved.

**Comment by mvl22** [comment]
> I've tried the latest build on an S3 and not found any regressions - nice work.

@jezhiggins Are we happy that we have a build now? Seems we have a useful milestone for a 'bugfix' release so that other work builds on that clean release point.
