### ISSUE TITLE
Registration confirmation email sent by V2 API provides a broken link for validation

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#138]
I've tried to register a number of accounts - using my own API key against the REST endpoint, and through the app.  I receive the "Confirmation email has been sent" message, but no confirmation emails have been received.  As a result:
-  I can't verify any authenticated endpoints that I'm migrating to Retrofit.
-  I'm concerned there may be a wider issue affecting users.

(As a side note, is this the right place to raise issues with the CycleStreets servers themselves?)

Maybe I'm being impatient? but I have waited a couple of hours and I believe most users would expect an almost-instant email ✉️  I don't know what the expectation is, perhaps @mvl22 or @jezhiggins could enlighten me here.

**Comment by mvl22** [comment]
I got a bounce from

`"youraddress@example.com"@localhost`

where your address is your actual address. I haven't seen this with the main website.

Can you check that you are sending the right data?

**Comment by oliverlockwood** [comment]
@mvl22 I've just emailed you about this with my actual email address to make sure we're talking about the same thing.
The `@localhost` bit is weird, I've no idea where that would have come from...

**Comment by mvl22** [comment]
Localhost would be added to the mailserver if it sees only a local part of the address.

I suspect you are sending a quoted string, i.e. `"youraddress@example.com"` rather than a string on its own, i.e. `youraddress@example.com`. Could you check?

`"youraddress@example.com"` would be interpreted I believe by
http://tools.ietf.org/html/rfc2822#section-3.4.1
as a local part because that seems to say that a @ in a quoted string would be treated as just any other character within the local part, not the @ delimiter.

On the other hand this could be a bug at the API end but as I say, I would expect to see that with other clients if so.

**Comment by oliverlockwood** [comment]
Some progress on this one.
-  It seems like I might have messed things up in my early attempts to integrate with the create user API, and so subsequent attempts for the same email addresses didn't work.
-  I registered through the app for my `@sky.uk` email address, and that worked fine (using the V1 API, of course).  The email came through, I was able to validate the account and that's now being used to verify the "authenticate" API in integration testing.
-  Running out of email addresses, I registered through the integration testing of the V2 API for my wife's email address (which should be fairly obvious from your logs).  The email came through, however the validation link (https://api.cyclestreets.net/signin/register/<UID>/) says `404 https resource not found`.

Since the V1 API currently used by the app gave a different form of link (https://www.cyclestreets.net/signin/register/<UID>/), I suspect this *is* a bug with the V2 API.

Interestingly, when I replaced "api" with "www" in the broken link provided by email from the V2 API, the validation worked.  So the server fix for this may be just to change the link that's being generated by the V2 API, or it may be more complex (without seeing the code for this, I can't tell).

It's worth highlighting that the Android app code that's currently in `master` should ***not*** be published as an app release until this issue is resolved.

**Comment by mvl22** [comment]
> I suspect this is a bug with the V2 API

Yes, you're right there may well be a bug with the hostname. Can you forward the e-mail you got so I can resolve this?

I think you're the first user of that V2 call - surprised we didn't spot this.

**Comment by oliverlockwood** [comment]
No worries, email forwarded as requested.  Let me know if I can be of any further help with this issue.

**Comment by mvl22** [comment]
Should be fine now. Thanks for spotting this.

**Comment by oliverlockwood** [comment]
Confirmed now as resolved, so I'm closing this issue accordingly.  Nice work to fix this so quickly! 👍
