### ISSUE TITLE
[Process] Run CI builds on PR branches

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#149]
So that we have a chance to verify whether a PR is going to break our builds, before we press the green button.

**Comment by mvl22** [comment]
Let me know if an account of some kind needs to be set up and I'll do this with our official e-mail address.

**Comment by oliverlockwood** [comment]
This is now done using [Travis CI](https://travis-ci.org/cyclestreets/android/builds) so I'm closing this issue as complete.
