### ISSUE TITLE
Rotating map view when location and orientation is being tracked

### ISSUE THREAD

**Issue by jf1** [cyclestreets/android#155]
OsmAnd does an excellent job of rotating a pre-downloaded vector map as you cycle, so it's what I now use whenever my phone is handlebar-mounted. It'd be great if the Cyclestreets Android app could do similar in future. https://github.com/osmandapp/Osmand

**Comment by mvl22** [comment]
Looks like the Mapsforge library we are using may have support now.

Refs:

https://github.com/mapsforge/mapsforge/issues/637
https://github.com/mapsforge/mapsforge/issues/7

**Comment by mvl22** [comment]
Another user request for this just came in:

`When using live ride it would be good if the cycling direction was always oriented towards the top of the screen on a smartphone. Is that possible?`

**Comment by jezhiggins** [comment]
Now tracked in issue #391
