### ISSUE TITLE
Feedback regression

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#157]
The "Comment on this route" system currently fails when clicking "Upload!" with "There was a problem sending your comments: null"

Reported in different issue #71.

**Comment by oliverlockwood** [comment]
I've started looking at this.  The problem is an `android.os.NetworkOnMainThreadException`, which has no detail message (hence "null").

We obviously need to send feedback in an async fashion.  I'll look into how this can be achieved.

**Comment by oliverlockwood** [comment]
The `Route.plotRoute()` does an asynchronous execution and could be used as an alternative.

**Comment by oliverlockwood** [comment]
Should be fixed in #162, once that one's been merged.

**Comment by jezhiggins** [comment]
> Should be fixed in #162, once that one's been merged.

Top stuff!
