### ISSUE TITLE
Move hardcoded strings into resource file

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#160]
Some strings are in a resource file, allowing them to be localised, as per e.g. https://github.com/cyclestreets/android/pull/158

Some strings are hardcoded, meaning they're always in English.  This isn't very nice to our non-English speaking friends, and we should fix it.

**Comment by oliverlockwood** [comment]
@rodrigo-brito once we've addressed this, would you be able to provide the additional translations into Portuguese, please? Thanks!

**Comment by rodrigo-brito** [comment]
No problem, I do.

**Comment by rodrigo-brito** [comment]
Uma sugestão: Coloquem o label "hacktoberfest" em uma issue de tradução, esse mês está acontecendo um evento de contribuição no GitHub, em menos de 1 dia o app vai estar traduzido para mais de 10 línguas diferentes.

**Comment by mvl22** [comment]
I'll get Transifex account set up.

**Comment by oliverlockwood** [comment]
Good suggestion @rodrigo-brito.

I'm going to try to work through the extraction of hardcoded strings in the next few days so we can take advantage of this.  #164 was the first step in this direction.

A further thought on string identification arose, as I nearly ended up with a conflict of strings named `photo_upload` being defined in both `cyclestreets-view` and `cyclestreets.vNext`, which would have caused problems.  I wondered if it might be worth prefixing things in a module-specific and logical manner, along the lines of the convention proposed by http://jeroenmols.com/blog/2016/03/07/resourcenaming/, potentially with a prefix of `cs_core_`, `cs_view_`, etc?

@jezhiggins, @mvl22 - can I have your thoughts on this ASAP (ideally today, so I can start some of this on the train home) so we can get a strategy defined before I spend time doing the rest of the string extraction?

**Comment by mvl22** [comment]
Side point: presumably `cyclestreets.vNext` is the actual library? I assume the naming came from a period of refactoring but that it might be better to fix this at some point.

Jez I think is best-placed to answer the main question. To a non-Android expert though, that link you sent looks sensible.

**Comment by oliverlockwood** [comment]
`vNext` is the actual Android app itself (I don't know why it's called that - Jez?)

The other modules (`view`, `core` etc.) are libraries.

To add to my previous comment, it looks like some of the string naming already follows this convention to a degree (e.g. https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/values/strings.xml#L50-L59 for the `PlaceView`) so unless I hear otherwise from Jez I'll go down the route of that convention without additional `cs_view` etc. prefixes.

**Comment by jezhiggins** [comment]
vNext is a bit of a historical hangover - we can (and probably should) drop that suffix now.  Goes back to when I was breaking up the application into the various libraries. 

Yes, the Mols scheme looks sensible to me.  Please go ahead.

**Comment by oliverlockwood** [comment]
This work is now complete, so I'm going to close this issue.

@rodrigo-brito please note that https://github.com/cyclestreets/android/issues/171 is ready for you to work on - if you'd like to complete what you've started with the Portuguese translations!
