### ISSUE TITLE
Publish beta builds using official Android methods

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#179]
We should do this.

We'll need to decide whether we want open or closed beta testing.
(see https://support.google.com/googleplay/android-developer/answer/3131213?hl=en-GB).

**Comment by jezhiggins** [comment]
Sorry, this ticket has passed me by.  The cyclestreets app is set to open betas, because closed is such a massive pain in the arse to sign people up to, but it's not publicised.

**Comment by mvl22** [comment]
Great; looking forward to seeing this in the beta store (or whatever it's called!).

**Comment by oliverlockwood** [comment]
I believe this is now working.  Each new build should automatically go to the Play store as a beta.  Two iterations of version 3.7 were published there this morning and I've downloaded them on my phone successfully.

Closing this issue accordingly.

**Comment by mvl22** [comment]
Great. Can you give a quick set of instructions as to how to sign up and get the beta?

**Comment by jezhiggins** [comment]
See https://support.google.com/googleplay/answer/7003180?hl=en-GB

**Comment by mvl22** [comment]
Thanks all for your efforts on this - really great that we now have this new official channel. I'll do a quick blog post on this soon.

**Comment by oliverlockwood** [comment]
:+1:

**Comment by mvl22** [comment]
I'll try and get this blog post done tomorrow. (If you want to help me expedite this, some screenshots and text would be great.)

**Comment by oliverlockwood** [comment]
I'll aim to do the screenshots ASAP. 

I reckon it would be worth holding off publishing the blog post until the new release is live (hopefully early next week if there's no more major issues uncovered).

**Comment by mvl22** [comment]
> I reckon it would be worth holding off publishing the blog post until the new release is live

I was thinking the opposite - it would be good to have more testers!

**Comment by oliverlockwood** [comment]
I guess it depends on whether you consider your audience to be beta testers, or general users and potential users.

**Comment by mvl22** [comment]
The blog post will be aimed at beta testers, yes.

**Comment by mvl22** [comment]
Any chance of these "How to sign up for the beta" screenshots? I've got the others now - thanks.

**Comment by oliverlockwood** [comment]
@mvl22 we've already given instructions for that above and by email to Simon (on your shared email address)...

**Comment by mvl22** [comment]
Blog post now at:
https://www.cyclestreets.net/blog/2018/08/31/android-app-beta-programme/

Let me know of any clarifications or changes.
