### ISSUE TITLE
Bump minSdkVersion?

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#189]
We could consider bumping the `minSdkVersion` (currently 14)
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

From a look at the dashboards right now:
-  0.6% of our users are on SDK 14 or below
-  1% of our users are on SDK 15 or below
-  3.3% of our users are on SDK 16 or below
-  6.1% of our users are on SDK 17 or below

**Comment by jezhiggins** [comment]
In the past, I've always used 5% as the level below which we should stop worrying about an Android version, so if there's a reason to move then go for it.

**Comment by mvl22** [comment]
Jez' rule of thumb seems good, and sounds like Oliver is thinking along the same lines.

I'm really keen that we modernise the look and feel of the app, so remaining on an old SDK level which prevents that should be avoided.

**Comment by oliverlockwood** [comment]
I've expanded the chart above to cover a couple more levels.  Based on this I will update the minSdkVersion to 17, so dropping new releases for 3.3% of our current user base.

Regarding modernising the look and feel of the app (which is currently generating a reasonable amount of negativity), a while ago you mentioned there had was going to be some wireframing of a new design, etc.  Has there been any progress this?

**Comment by mvl22** [comment]
> Has there been any progress this?

Yes, we got a long way through discussing how things should be but haven't yet got these written down as drawn wireframes. Action on this likely soon, pending availability of a key person.

I'd say main thing at this stage is to get the underlying system like API, layout drawing system, etc., as modernised as possible so that the redesign will be much quicker to put into place.

**Comment by oliverlockwood** [comment]
>Yes, we got a long way through discussing how things should be but haven't yet got these written down as drawn wireframes. Action on this likely soon, pending availability of a key person.

Good news, I look forward to seeing what comes out!

>I'd say main thing at this stage is to get the underlying system like API, layout drawing system, etc., as modernised as possible so that the redesign will be much quicker to put into place.

That suits me fine.  I'll keep iterating on these aspects as and when I can spare the time.  As I've spent my dev career doing mostly back-end software this is what I'm better suited for - I'm likely to be less capable at helping with UI stuff.

As per the PR that's been merged, we're now on a `minSdkVersion` of 17.  If when we do a redesign it looks like our lives would be made a lot better by bumping this one version further, I think we should give it serious consideration, but I think there's no immediate need to do so just now.

**Comment by oliverlockwood** [comment]
As per the PR that's been merged, we're now on a `minSdkVersion` of 17.  If when we do a redesign it looks like our lives would be made a lot better by bumping this one version further, I think we should give it serious consideration, but I think there's no immediate need to do so just now.

Closing this issue for now.

**Comment by mvl22** [comment]
> Regarding modernising the look and feel of the app (which is currently generating a reasonable amount of negativity), a while ago you mentioned there had was going to be some wireframing of a new design, etc. Has there been any progress this?

A proposed design has been circulated on the mobile@ list now - do give thoughts.
