### ISSUE TITLE
Add elevation chart

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#193]
The iOS app and website currently have an elevation chart, but Android does not.

The journey planner API gives values for `elevations`. When combined with `distances` to get correct spacing, this enables a chart to be created.

https://cyclestreets.net/api/v1/journey/#sampleResults

```
"elevations":"9,9,10,10,10,10,10,10,10,9,9,9,9,9,9,9,9,8,8,8,8,7,7,7,7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,7,7,6,6,7,7,7,7,7,7,7,7,7,8,8,8,8,9,9,9,9,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,9,9,9,9,9,9,8,8,8,8,8,8,8,8,8,8,8,8,8,7,7,7,7,7,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,7,7,8,8,7,7,8,9,11,11,11,12,12,12,12,11,11,11,11,11,11,11,11,11,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,8,9,9,9,9,10,10,10,10,10,10,10,11,10,11,11,11,11,11,11,11,12,12,13,13,14,14",

"distances":"12,11,65,40,6,14,16,11,30,31,22,10,8,5,3,10,26,1,60,68,29,3,3,10,65,8,5,3,2,3,3,5,10,19,23,9,24,20,14,13,14,12,7,4,14,10,13,11,20,15,24,6,1,52,41,23,102,66,51,90,6,87,5,4,7,13,14,50,17,9,8,25,132,20,15,8,10,37,9,11,28,5,26,136,10,48,23,11,12,24,19,16,20,63,6,30,14,10,7,27,67,7,25,67,13,31,10,9,22,12,10,12,19,27,11,46,18,49,19,53,53,19,49,18,46,38,7,7,21,19,58,2,24,12,3,25,8,3,7,7,7,8,6,34,18,28,11,16,26,10,8,14,30,26,24,67,16,14,50,36,12,9,25,13,12,25,20,32,26,30,4,7,8,12,9,9,20,54,7,5,8,4,3,2,38,20,33,21,4,9,7,8,6,19,15,19,14,19,9,27,21,10,60,30,37,14,29,94,10,35,30,32,11,9,10,10,13,16,8,8,14,38,47,23,17,30,10,15,14,4,4,4,4,4,13,10,6,6,12,21,24,14,110,17,27,19,23,14,23,7,13,5,7,3,4,11,9,111,6,13,14,10,9,7,248,19,6,9,10,17,24,7,18,7,5,7,27,17,9,8,49,23,52,30,43,6",
```

![elevations](https://user-images.githubusercontent.com/361423/27858414-0b4fbea2-616d-11e7-9973-4e45df7f743e.jpg)

**Comment by smsm1** [comment]
The elevation is available on Android:

After creating an itiniery, swipe from the left to get the menu and choose "Itinerary":
![screenshot_20170705-103657](https://user-images.githubusercontent.com/82719/27858696-17165c54-616e-11e7-8ffc-70a7506ed75a.png)

In the top right there is an elevation button:
![screenshot_20170705-103653](https://user-images.githubusercontent.com/82719/27858739-42b478c8-616e-11e7-9648-6989e45e649a.png)

After tapping the elevation button you get the elevation shown:
![screenshot_20170705-103702](https://user-images.githubusercontent.com/82719/27858762-59c45b46-616e-11e7-89d8-e55f1ebd6a02.png)

**Comment by smsm1** [comment]
Making the elevation easier to get to would be a useful option, and having a feature to show the elevation on the map somehow would be interesting.
