### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by rugk** [cyclestreets/android#194]
Cyclestreets is currently not available on F-Droid. It would be nice to have it available there, too.

**Comment by mvl22** [comment]
F-Droid is the Free and Open Source Android App Repository.

This presumably enables people to download apps without needing to be signed in to the Google ecosystem, a concept which I endorse. So am certainly in favour of this ticket.

**Comment by rugk** [comment]
Of course it enables people to do that. See https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/ for an how-to.

**Comment by jf1** [comment]
+1 from me. I've previously suggested this, including for beta versions which now seemed to be better handled by Google's Play Store.

**Comment by oliverlockwood** [comment]
Marking this as "help wanted" as I don't think the core maintainers (such as we are) are likely to prioritise this in the near future.  @rugk, do you fancy contributing here?

**Comment by Rudloff** [comment]
The build recipe already exists in the F-Droid repository: https://gitlab.com/fdroid/fdroiddata/blob/4a24691702b54789904cb170f46c1788ae95697a/metadata/net.cyclestreets.txt
So it will be pretty easy to update once #84 is fixed.

**Comment by oliverlockwood** [comment]
@Rudloff @rugk - now that #84 is closed (in `master` source code and beta builds, if not full release builds), can this be resolved?  Or do we have to wait until we cut a release build?

**Comment by Rudloff** [comment]
We only package stable releases so it will have to wait until you publish a new release.

**Comment by mvl22** [comment]
Version 3.6 has just been released, by the way.

**Comment by mvl22** [comment]
> https://gitlab.com/fdroid/fdroiddata/blob/4a24691702b54789904cb170f46c1788ae95697a/metadata/net.cyclestreets.txt

NB A couple of URLs in that file need updating:

```
Web Site:http://www.cyclestreets.net/mobile
Source Code:https://github.com/cyclestreets/android
Issue Tracker:https://github.com/cyclestreets/android/issues
Changelog:https://github.com/cyclestreets/android/raw/HEAD/assets/whatsnew.html
Donate:http://www.cyclestreets.net/donate
```

Should now be

```
Web Site:https://www.cyclestreets.net/mobile/
Source Code:https://github.com/cyclestreets/android
Issue Tracker:https://github.com/cyclestreets/android/issues
Changelog:https://github.com/cyclestreets/android/raw/HEAD/assets/whatsnew.html
Donate:https://www.cyclestreets.net/donate/
```

**Comment by Rudloff** [comment]
> Version 3.6 has just been released, by the way.

Yes, but it does not include the #84 fix.

**Comment by oliverlockwood** [comment]
Cool.  I'll keep track of this and once 3.7 is released I'll try raising a PR against Fdroid.

**Comment by oliverlockwood** [comment]
@jf1  @Rudloff @rugk with apologies for taking literally years to achieve this: version 3.7 is now live in the play store.  The Git tag is `RELEASE_3_7`.  Please go ahead and update F-droid to pick this up - I'm afraid I don't have the energy or inclination to read up how to do this myself!

I'm going to close this issue now as there's nothing stopping it being made available there.

**Comment by mvl22** [comment]
In terms of the metadata:

- `AuthorWebSite`: This is now https://www.cyclestreets.org/ (this is the organisation's overall website, not the CycleStreets journey planner -specific site)
- `Donate`: This is now https://www.cyclestreets.org/donate/
- `AuthorEmail`: We'd prefer not to have this set if possible - we try to reduce instances of our e-mail address around the web as it just attracts spam.

**Comment by Rudloff** [comment]
I added 3.7 here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6712

**Comment by mvl22** [comment]
Thanks so much!

Let us know when this is ready and I'll publicise this on our Twitter channel.
