### ISSUE TITLE
Request permissions for contacts on-demand

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#195]
The app has route-to-contacts feature, so people can for instance get the route to a friend's house.

Currently I believe the app requests general contacts permissions up-front at the time of installation from the app store. Users wonder why this is needed, potentially reducing trust. We've certainly had support requests as to whether we upload contacts to servers (which we don't, and have no support or desire to do).

We should instead move to the on-demand model, where permission is requested at the point that the permission is needed.

As stated in the privacy policy:

`CycleStreets apps that request access to the user's address book have this functionality purely so that the user can do 'route to address'. Apps do not, and are unable to, upload any such data to the CycleStreets server. This can be independently verified by viewing the source code of our apps.`

**Comment by jezhiggins** [comment]
The Android permissions model has changed over time. As we move to build for more recent versions, we will automatically move to permissions on-demand.

**Comment by mvl22** [comment]
Are we any nearer to having this supported? The current download does still ask for Contacts up-front, and I'd really like to get rid of this if we can now have it request at the point of the user going to contacts.

**Comment by oliverlockwood** [comment]
I'm working on this alongside what I'm doing for #258.  It's not just for contacts, but for other permissions (read/write external storage, location, etc) which this needs some work.

**Comment by oliverlockwood** [comment]
As noted in #255, we actually have a problem here where we never even ask for the permissions (we just disable the feature).  I'm working on it.
