### ISSUE TITLE
Improve GUI

### ISSUE THREAD

**Issue by rugk** [cyclestreets/android#197]
Are the screenshots on [this site](https://www.cyclestreets.net/mobile/android/) actually up-to-date? If so, hey, this is really a nostalgic Android 2 (or so) style… 😊

Nice, but to be serious: You should update your UI. Material style would be an aim, or something similar… Look how other apps (open source, e.g.: Maps.me; OsmAnd) do it.

**Comment by mvl22** [comment]
This is actually in progress right now. E-mail us with your address and I can give access to our mobile discussion list where a new prototype UI that has been created last month is being discussed. This will be doing to a designer soon.

**Comment by rugk** [comment]
See my GitHub profile for address.

**Comment by rugk** [comment]
However, as a different question: Why not design/develop openly somehow/somewhere? I mean this is an open-source project, after all.

**Comment by mvl22** [comment]
Yes, virtually everything is now discussed here in tickets. But this is for a cross-platform redesign and at this earlier stage of discussing the prototype conceptually we are keen to discuss with heavily involved people so far and then open up the design for further discussion.

**Comment by oliverlockwood** [comment]
@mvl22 I'm a bit late in pointing this out, but the app hasn't looked like [the link @rugk posted](https://www.cyclestreets.net/mobile/android/) in years.  On the other hand, the [Play store](https://play.google.com/store/apps/details?id=net.cyclestreet) representation is reasonably up-to-date. 
 That does make me ask the question:

1.  Is that page really useful in a standalone way?  If so, how should we get it (and subsequently keep it) up to date?
2.  Alternatively, could we not just link to the Play store page for images, app details etc, so there's something closer to a single source of truth?

**Comment by mvl22** [comment]
If you could make me some screenshots representing the best parts of the app (and ensuring that the places shown are famous places, e.g. in London, not random villages that people can't identify with), I'll get the main site page fixed up.

**Comment by oliverlockwood** [comment]
#257 covers taking screenshots etc.  The upcoming release upgrades the UI significantly also.  I'll close this issue accordingly.
