### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [cyclestreets/android#201]
Hello I would like to contribute with a new icon and logo for your application I leave you the proposal if you want to use it I can send you all the files.

![presentacion para github.png](https://steemitimages.com/DQmWZ11kbCF9VnXwi6q8dsfZdgJfEvuJvcxWTs35eJse5pw/presentacion%20para%20github.png)

**Comment by oliverlockwood** [comment]
Hi @richardbmx - thanks for the contribution idea. The logo for this app derives from the logo of https://www.cyclestreets.net/ - it's not standalone for Android.  So it's really a question out of scope for this repo.

@mvl22 do you have somewhere broader to consider such changes?  I'll leave this in your hands as I'm sure you're better placed to assess things across the wider Cyclestreets estate, I'm just an Android chap 😉

**Comment by mvl22** [comment]
Dear richardbmx,

Thanks for this contribution. As Oliver says, our logo and icon is based on our overall brand, and we do not have any plans to change that.
