### ISSUE TITLE
If location permission not granted, completely disable affected features (e.g. LiveRide) 

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#204]
This came out of discussions on #202.

**Comment by jf1** [comment]
I frequently have location disabled so hope there'll be a straightforward way to access those features if location is enabled once Cyclestreets is running, ie please don't disable then not re-check until restart, or add a manual way to trigger a re-check.

**Comment by oliverlockwood** [comment]
@jf1 this isn't about location enabled/disabled, it's about the *permission* for an app to use location information.  I'd be surprised if anyone frequently revokes/allows such permission 😃

**Comment by oliverlockwood** [comment]
Note that after #265 has gone in, the RouteMapFragment will remain be the only place that requests permissions at fragment startup, rather than when we attempt to use a particular feature.  I'll look into sorting this (alongside the specific LiveRide enabling/disabling issue described here) soon.

**Comment by oliverlockwood** [comment]
#269 deals with the location permission.

That leaves us with the write data permission, which the `RouteMapFragment` still demands at startup time (for saving map tiles).

I'll look into what we can do here.
