### ISSUE TITLE
Android 8.0 (API level 26) from August 1, 2018

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#214]
"Google Play will require that new apps target at least Android 8.0 (API level 26) from August 1, 2018, and that app updates target Android 8.0 from November 1, 2018."

https://developer.android.com/distribute/best-practices/develop/target-sdk

How near are we on that?

**Comment by oliverlockwood** [comment]
See https://github.com/cyclestreets/android/blob/master/config.properties#L13-L15.

At the time of writing this:
>```
>compileSdkVersion=26
>minSdkVersion=23
>targetSdkVersion=23
>```

Thanks for raising this issue.  There's clearly some work for us to do before November.

**Comment by oliverlockwood** [comment]
When we update this, it might be worth raising the minSdkVersion to 24 as well, as this allows a whole bunch more useful language features (Java 8 e.g. default methods on interfaces, etc.)

**Comment by mvl22** [comment]
> minSdkVersion to 24

I believe that takes us to Android 7.0 released on August 22, 2016. That seems quite recent to me, and I suspect will cut a significant amount of our current userbase out. I think we'd need a very good reason to do that beyond just coding purity.

**Comment by oliverlockwood** [comment]
Fair point!
