### ISSUE TITLE
Profile roughness means total elevation gain/loss calculations are inaccurate

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#222]
Follows on from #219.

I had a suspicion that the total elevation calculations were a little off.
It occurred to me today to test this with a known example.  I took Alpe d'Huez.  According to https://www.cyclinglocations.com/alpe-dhuez-climb-alps/, the total elevation gained is 1135m.  According to us, it's almost twice that:

<img src="https://user-images.githubusercontent.com/6017680/42555122-1b29f9b4-84df-11e8-81da-5a5529f5eedb.png" width="270" height="480">

With this graph showing a relatively short distance, you can clearly see that this inaccuracy is caused not by an incorrect algorithm but by slightly ropey data.

@mvl22, @jezhiggins, two things:

1.  In the screenshot above, you can see the PR we were discussing yesterday, as visualised on my actual phone.  Please do download the updated beta and see what you think.  (Given that the styling refresh currently being discussed has no elevation profile view defined yet, perhaps this should be presented as a starting point - not perfect but a stake in the ground.)

2.  Regarding the erroneously jagged profile of this climb (I've ridden up Alpe d'Huez, it's very much not like this 😄) - have you any thoughts?  Is there something we should do on the server side to improve this?  Or would you rather have the client device perform some sort of mathematical smoothing operation?  If the latter, I'd welcome suggestions, as the relevant modules of my engineering degree have faded to a somewhat vague state through lack of use...

**Comment by jezhiggins** [comment]
Isn't this just a difference of presentation?

On the link you give the starting altitude is 725m, the final altitude is 1860m, and they're clearly working out the elevation gained of 1135m by doing 1860-725.

While I recognise that your experience of the Alpe d'Huez isn't jagged, is it really a non-stop monotonically increasing climb? I suspect not. 

For the elevation calculation from the route data, we're adding up all the tiny increments over each segment. In this case that adds up to 2255m, which looks outrageous - nearly twice the actual elevation.  However, we've summed up all the tiny declines too, which here add to 1129m.  Comparing our 2255 with 1135 isn't comparing like with like. The figure above is "how much higher am I at the end of the ride than at the beginning?"  Our figure is, kind of, how much does the road go up and down on my way.  Well, it goes up 2255m and it comes down 1129m, leaving me 1124m higher than I started.  1124m is within error of 1135m

Consider a circular route - the elevation gain, by definition, must be zero.  However, you've almost certainly gone up a bit and down a bit on the way round. 

I don't think the data is wonky. Perhaps we're just not calculating what you think we're calculating (or what we should be calculating).

**Comment by oliverlockwood** [comment]
@jezhiggins thanks for your detailed thoughts.

After having had 4 days on tour with this feature, here's my update.

1.  The route profiles and total elevation gain/loss seem plausible in the UK; both on the routes we were taking, and occasional playing around planning routes on specific hills such as Bealach na Bà.  So perhaps this is only an issue outside of the UK.

2.  The route profile for Alpe d'Huez is *definitely* a long way off.  I certainly don't believe that Google is the fount of all knowledge, but [planning the same route on Google Maps](https://www.google.com/maps/dir/45.0597324,6.037812/45.0931087,6.0673852/@45.0773902,6.0494629,15.03z/data=!4m39!4m38!1m35!3m4!1m2!1d6.0408431!2d45.0692309!3s0x478a6bf7578b18d7:0x6e1496b135bc8a0f!3m4!1m2!1d6.0442735!2d45.0709395!3s0x478a6bf1a32a8841:0xaf43ceac6c569bbf!3m4!1m2!1d6.0503398!2d45.0734565!3s0x478a6bf276066f8f:0x3b2c11a6f45ce90f!3m4!1m2!1d6.0619207!2d45.0820466!3s0x478a6b9622340c69:0x41895230196fde06!3m4!1m2!1d6.0561808!2d45.0882438!3s0x478a6bb8c214570b:0xab10bc4b8d13f2e9!3m4!1m2!1d6.0597871!2d45.0915858!3s0x478a6bb9d050c657:0xd3769e3baeccac66!3m4!1m2!1d6.0616279!2d45.092652!3s0x478a6bb751af1d9f:0x3488b7a99500eab3!1m0!3e1) gives a total elevation gain of 1157m and a loss of 53m, which is entirely plausible.  The idea that an *ascent* of Alpe d'Huez involves descending by *over a kilometre in height* is crazy... and if you're still not convinced, then I invite you to watch tomorrow's Tour stage going up it 😃 https://www.letour.fr/en/stage-12

While making this point, it occurred to me to zoom in on some of the Alpe d'Huez climb.  I took a short section - two switchbacks connected by one hairpin bend in the middle - and here's the profile that we're presented with:
<img src="https://user-images.githubusercontent.com/6017680/42865636-2e4d1fc0-8a62-11e8-96d5-4286c1da5f50.png" width="270" height="480">

You can inspect the raw data which provides this - to prove that it's not the app doing something wrong! by hitting https://www.cyclestreets.net/api/journey.json?plan=balanced&itinerary=61717148&key=redacted
An example (from reading through the data points) is a 61m altitude change in 9 horizontal metres.

On the basis that this is clearly nonsense, I'm curious @mvl22 where does the various mapping data come from?  Is it just that the data we have for the UK is of a much higher quality than that for France?

**Comment by mvl22** [comment]
A range of elevation data sources are used, and the UK area will be better than France at the moment. However, we are constantly improving things in this area, so please just plan a route and use the route feedback button whenever you find a poor result and we can look into this. We have applied fixes, data source changes and algorithm/interpolation improvements over the years, so it’s definitely worth reporting problematic routes.

**Comment by oliverlockwood** [comment]
@mvl22 I'd love to give feedback that way, but I can't persuade the "Comment on this route" menu item to appear on my phone.  Does that work for you, or do we need to raise an issue and fix a bug?

(I'll start having a dig through the code shortly.)

**Comment by mvl22** [comment]
I think it's on the Android secondary button menu, which of course is increasingly undiscoverable.

The new UI design obviously solves this by not having anything hidden in that way. But for now, feel free to create a new issue to put a button somewhere!

**Comment by oliverlockwood** [comment]
Since this is a localised issue of poor data, and that's been reported, I'm going to close this issue for now.

**Comment by mvl22** [comment]
Thanks; yes, safely received. @si-the-pie will have a look at this when he next gets a chance.

Do submit any further cases you find.
