### ISSUE TITLE
Change website link displayed in POI bubbles to be clickable short text

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#227]
... instead of a non-clickable, potentially verbose, full URL.

As suggested by @mvl22 when reviewing #224.

**Comment by oliverlockwood** [comment]
Some websites are so long you have to scroll the map in order to view them.  We should really solve this.

**Comment by oliverlockwood** [comment]
@HilaryN is this something you fancy working on?

**Comment by HilaryN** [comment]
Could do, yes.

**Comment by HilaryN** [comment]
Keeping it simple for starters, I've changed the URL to "Tap here to show website".  If you tap anywhere in the bubble it will display the website in a browser.  Here are some examples:

<img width="749" alt="Test POI link 1" src="https://user-images.githubusercontent.com/59799824/84712509-af3db700-af60-11ea-9aa6-0d5967266c31.PNG">
<img width="741" alt="Test POI link 2" src="https://user-images.githubusercontent.com/59799824/84712518-b6fd5b80-af60-11ea-941c-7001be5f45a9.PNG">

On returning to Cyclestreets, the bubble is hidden:

<img width="741" alt="Test POI link 4" src="https://user-images.githubusercontent.com/59799824/84712620-f166f880-af60-11ea-8975-9821f88a8f0a.PNG">
<img width="464" alt="Test POI link 5" src="https://user-images.githubusercontent.com/59799824/84712630-f6c44300-af60-11ea-812a-d63f64b77c74.PNG">

If there is no website the "Tap here..." isn't displayed.  (Tapping the bubble hides it as at present.)

<img width="463" alt="Test POI link 3" src="https://user-images.githubusercontent.com/59799824/84712549-cbd9ef00-af60-11ea-999f-5d6c18bce412.PNG">
