### ISSUE TITLE
Navigation bar regression

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#231]
I spotted that the current beta has a regression in the top navigation bar.

### Before
<img width="272" alt="screen shot 2018-07-20 at 19 40 01" src="https://user-images.githubusercontent.com/6017680/43020180-219119ca-8c57-11e8-9f4e-b5f136a50a1c.png">
<img width="275" alt="screen shot 2018-07-20 at 19 39 53" src="https://user-images.githubusercontent.com/6017680/43020181-21ac5f78-8c57-11e8-8045-e645f22c8754.png">

### After
<img width="272" alt="screen shot 2018-07-20 at 19 41 58" src="https://user-images.githubusercontent.com/6017680/43020178-21580fcc-8c57-11e8-888e-31c53b2205e3.png">
<img width="270" alt="screen shot 2018-07-20 at 19 41 51" src="https://user-images.githubusercontent.com/6017680/43020179-2175ca44-8c57-11e8-8550-d28a547f0108.png">

### Digging into it
I used `git bisect` and, taking account for non-compiling intermediate commits (which predate when we enforced squash-merging of PRs), the following set of changes is to blame:
https://github.com/cyclestreets/android/compare/464d819...588f25e

From this, I suspect it's most likely to be a problem resulting from either:
-  updating the `compileSdkVersion` from `19` to `23`, or
-  upgrading the `com.android.support:appcompat-v7:20.+` dependency to `23.4.0`.

I currently know very little about how the top navigation drawer is drawn and animated.  I don't suppose @jezhiggins you might be able to help track down this regression or at least give me some pointers, please?

**Comment by oliverlockwood** [comment]
I have been mulling over this... maybe it's time to bite the bullet and upgrade the navigation bar to material style, fully?

It may or may not be easiest to build the new navbar from scratch.  Just an idea.

**Comment by jezhiggins** [comment]
I noticed it at the time I made the change, but decided it wasn't worth chasing at that point given imminent redesign.

I think this is the intended behaviour of appcompat - you can find the same arrow all over the place - and I have a suspicion that the behaviour we had before (which I liked!) was probably by accident. 

While the new behaviour is what we want in some places - Settings, Photo Upload - it isn't in others.  I think rebuilding the navbar is probably the way through this.

**Comment by oliverlockwood** [comment]
@mvl22 while I'm in the process of fixing this with a more modern approach, it occurred to me that we could start to restyle the app a little in colours, logos etc. as per the redesign that has been under discussion for some time.

Do you have a finalised colour palette and set of logos / non-standard icons that I can begin working with?  I feel like I might as well do that rather than style the new navigation drawer according to the old design, and then just rework it in a few months.

**Comment by mvl22** [comment]
I'd prefer we didn't end up with a sort of zombie design where bits of the new design co-exist with the old design. I really appreciate your enthusiasm to think of this though!

Will it be a lot of work to get something like existing design working with the new code? Obviously I am keen not to waste your time but just wary of having the new design work implemented on only a fractional basis.

NB I'm not too worried about the missing icon either... As long as we have something working acceptable for the next release, that's fine.

**Comment by oliverlockwood** [comment]
@mvl22 no worries, that's fine.  I'll update this PR so it can still move forward towards Material styling patterns without changing the current colour palette and icons.
