### ISSUE TITLE
API 'Latest news' message dialog system

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#25]
It would be useful to be able to send occasional messages to users, e.g. that CycleStreets needs votes for a funding award, etc.

Needs API provisioning but that should not be hard.

**Comment by oliverlockwood** [comment]
I can't figure out why this ticket should still be open.  Accordingly I'm closing it.  @mvl22 please re-raise anything outstanding; we've had the blog in the app since before I got involved.

**Comment by mvl22** [comment]
No, this is all great - no problems! Agree this should be closed.

I think the blog did come after this report was in.
