### ISSUE TITLE
New screenshots for page on CycleStreets website

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#257]
This issue is to get some new screenshots to replace the ancient ones at:
https://www.cyclestreets.net/mobile/android/

A reminder that a good screenshot contains places that are more likely to be recognisable to a larger number of people, e.g. central London's Downing Street or the Bullring in area in Birmingham, rather than an obscure village. For screenshots from the Photomap, good, positive images, like people without helmets/hi-viz of various genders using a cycle superhighway, would be good.

**Comment by oliverlockwood** [comment]
I think:
1. We should get new screenshots
2.  Perhaps you'd like to do the honours?
3.  As mentioned in the other issue on the subject, we should update the images on the play store but I believe *the cyclestreets page should refer to this for its images*. Otherwise we have two sources of truth to maintain, no?

**Comment by oliverlockwood** [comment]
Marking this as milestone 3.7 (since we'll do it *after* we're ready to release 3.6, even though it relates to release 3.6).

**Comment by mvl22** [comment]
As I don't currently have a modern-enough Android, I'd be grateful if you could make and e-mail me some screenshots, so that I can update the page on the CycleStreets website.

See note above about recognisable locations.

**Comment by oliverlockwood** [comment]
@mvl22 did you see my comment above about trying to avoid having two separate sources of truth for the images?
>we should update the images on the Play store but I believe the Cyclestreets web page should refer to this for its images, to avoid duplication

**Comment by mvl22** [comment]
Yes, sorry was actually just editing my comment accordingly...! Here's what I have just rewritten:

Yes, I'll use ones that get submitted to the Android Play store. See note above about recognisable locations.

However, I suggest shifting this down to 3.6, as the release should be accompanied by updated screenshots. The ones there are old and have random unrecognisable places.

**Comment by oliverlockwood** [comment]
@mvl22 now that you've got a load of relevant screenshots, and I've updated the [Play Store entry](https://play.google.com/store/apps/details?id=net.cyclestreets) with them, can you please get https://www.cyclestreets.net/mobile/android/ updated accordingly ASAP?

**Comment by oliverlockwood** [comment]
@mvl22 has done this now.  Closing the issue accordingly.
