### ISSUE TITLE
Server: moderation of photo submissions?

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#266]
@mvl22 - one for your consideration.

I've realised, while doing testing of the Add Photo submission, that there doesn't seem to be any pre-publication moderation, before the content becomes visible.   (I don't know whether any retrospective moderation is performed.)

For example, this beauty showing my laptop and my leg: https://www.cyclestreets.net/location/101617/

-  If it is simply a case that I'm a "trusted" user and as such not moderated, then it's probably worth you just deleting everything I've uploaded (since I've never submitted a cycling-related shot, I've only ever done testing pieces).

-  If the same unmoderated model is used for all users, is CycleStreets exposed to a risk whereby users submit unpleasant or illegal content and it's instantly available for all to see?

What are your thoughts?

**Comment by mvl22** [comment]
We have a mechanism in place which I can explain over e-mail.

Please log into the site and delete your temporary images.

**Comment by oliverlockwood** [comment]
Done and done.
