### ISSUE TITLE
ACRA reports don't reach developers

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#267]
We have ACRA crash reporting set up.

As a developer, I'm not seeing these crash reports, even when I've put comments in there saying "please forward to <my email address>".

We should look into the configuration of how these reports are submitted, and consider updating it.  In any case I believe the ACRA dependency we have is quite old, and we should update this as part of that work.

**Comment by mvl22** [comment]
If these come by e-mail, please ensure this is an official address under our domain. We can set up aliases easily if I know what’s needed.

**Comment by jezhiggins** [comment]
The ACRA reports were setup to push to a Google spreadsheet.  Now that Android's own support for crash reports a) exists and b) seems to be reasonable, we might not need ACRA at all any more.
