### ISSUE TITLE
Update Launcher icon

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#270]
The current, square-only form of the launcher icon looks a bit rubbish on phones with API level >=26.
<img width="287" alt="screen shot 2018-08-17 at 21 11 03" src="https://user-images.githubusercontent.com/6017680/44286907-a09df000-a262-11e8-846d-e4a9960fe337.png">

We should improve this.

**Comment by mvl22** [comment]
The original logo file is at:

https://www.cyclestreets.net/images/logo/download/CycleStreetsLogo.pdf
https://www.cyclestreets.net/images/logo/download/CycleStreetsLogo.ai
https://www.cyclestreets.net/images/logo/download/CycleStreetsLogo.tif

but I think we should use the same icon as the iPhone app, which I will need to fish out.

**Comment by mvl22** [comment]
![cyclestreets-1024-newicon](https://user-images.githubusercontent.com/361423/44303110-263ba180-a330-11e8-8ce4-9de1bd93a95e.png)
