### ISSUE TITLE
Elevation profile repeats distance axis labels on short route

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/android#280]
This shows the elevation profile for a [short route](https://www.cyclestreets.net/journey/63083493/#balanced) which had three waypoints.

The axis says "0 miles" twice - which is confusing.

The other problem is that "1 miles" (which also appears twice) should be singular.

This is related to: https://github.com/cyclestreets/android/pull/219

![screenshot_20180824-103846_cyclestreets](https://user-images.githubusercontent.com/361987/44587834-067f0000-a7ac-11e8-8309-68c8682ed085.jpg)

**Comment by oliverlockwood** [comment]
I *think* this is a pre-existing issue, not a regression, but I agree it's a bit rubbish.
