### ISSUE TITLE
LiveRide voice oddities

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/android#281]
The voice refers to itself as: Live (as in 'and Let Die') Ride, rather than: Live (as in 5) Ride.

On a short journey I hear the voice say: "One minutes"

An oddity is hearing: "Getting ready to arreeve eh" which I think is supposed to sound like the french word arrivé.

I want to tap on the screen for it to read out the last instruction again - or say to my phone: Pardon? / Can you say that again!

**Comment by oliverlockwood** [comment]
@si-the-pie - can you please raise the "I want to" as a separate issue with label `enhancement`?

I'll keep this issue to track the oddities.

**Comment by oliverlockwood** [comment]
@si-the-pie can you please review whether the latest build fixes these issues, please?

**Comment by oliverlockwood** [comment]
Scratch that, now it's pronouncing "live-uh" for me on my phone (although correctly on the app).  Another iteration under way.

**Comment by oliverlockwood** [comment]
Closing this as I believe it's now fixed.  @si-the-pie please reopen if you disagree.
