### ISSUE TITLE
Route finding failed

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/android#298]
I've been occasionally getting the 'Route finding failed' message after setting waypoints by tapping. Usually if I re-request a route then one does appear. But this time it did not, and below is the screen grab for Thoday Street, Cambridge.

That route generates this request (api key hidden):

`https://www.cyclestreets.net/api/journey.json?plan=balanced&itinerarypoints=0.1478084921836853%2C52.2000287382715%7C0.14693140983581543%2C52.198634652097525&speed=16&key=`

(incidentally it is only necessary to send co-ordinates rounded to five places of decimals, which is a lot easier to read)

and generates a route like this one: https://www.cyclestreets.net/journey/63122347/#balanced

so I don't think the error is from the CycleStreets server. I have been able to reproduce the problem by removing the waypoints and resetting them. Sometimes I get a route, sometimes not.

![screenshot_20180829-204753_cyclestreets](https://user-images.githubusercontent.com/361987/44816059-0f6f3780-abd9-11e8-818a-7f0de1864e0a.jpg)

**Comment by si-the-pie** [comment]
That related to version 1497, but I've just checked and get the same with version 1499.

**Comment by oliverlockwood** [comment]
Good catch, and thanks for the clear repro scenario.

After introducing some logging, I see this:

```
08-30 08:39:42.027 17102-17102/net.cyclestreets W/.routing.Route: Route finding failed
    java.lang.RuntimeException: Coding error - unable to parse domain JSON
        ...<stacktrace>...
```

Am digging into this.

**Comment by oliverlockwood** [comment]
The problem seems to be occur for single-segment routes - where our domain transformation produces JSON like this:
```json
  "segments": {
    "name": "Thoday Street",
    ...
  }
```

instead of:
```json
  "segments": [
    {
      "name": "Thoday Street",
      ...
    }
  ]
```

(and the domain object into which we're parsing expects the latter form).

**Comment by oliverlockwood** [comment]
Fix now ready for review.

**Comment by mvl22** [comment]
> The problem seems to be occur for single-segment routes - where our domain transformation produces JSON like this

Urgh yes, this is a long-standing bug in the output, resulting from the way the XML is serialised into JSON at the edge of the output.

This is all resolved in forthcoming V2.

**Comment by oliverlockwood** [comment]
@mvl22 as it happens, the server API response was fine; the bug was actually in the Jolt JSON-to-JSON transformer on the app.
