### ISSUE TITLE
Some segments have ridiculously long names

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#305]
See e.g. https://www.cyclestreets.net/api/journey.json?plan=balanced&itinerary=63125468&key=redacted

`Link joining Pedestrian Area, Link between Charlton Way, B210 and Pedestrian Area, Link joining Long Pond Road, General Wolfe Road, Pedestrian Area, Charlton Way, B210`

<img width="272" alt="screen shot 2018-08-30 at 14 11 09" src="https://user-images.githubusercontent.com/6017680/44853826-df6a7780-ac5e-11e8-844b-1d08d7d405ec.png">

It's a bit annoying visually, but when LiveRide reads it out, it's ridiculous.

I'd be inclined to suggest thresholding in LiveRide such that if a road contains too many words (say >12), that we cut it off after 12 words or two commas, whichever is less.

What do people think @mvl22 @si-the-pie @jezhiggins ?

**Comment by mvl22** [comment]
I think this is a scenario where there needs to be improved QA in OSM. Paths of any kind along a street should have the street's name added - this is a data error where this not the case.

Missing names for that particular case fixed up in:
https://www.openstreetmap.org/changeset/62141397

**Comment by oliverlockwood** [comment]
@mvl22 nice one for fixing that instance 👍

I'm also in favour of the post-processing you mention, but it doesn't sound like that's going to happen overnight.

In the meantime, I'm inclined still to implement a simple workaround such as that described above.

**Comment by mvl22** [comment]
Yes, happy to have a workaround.

I was thinking more about the ultimate cause of the problem, but realistically some kind of workaround like this is going to be needed, whether in the app or server-side. (We should probably just truncate these ourselves with "... and 3 other streets" for instance.)

**Comment by si-the-pie** [comment]
Yes I am happy that you do a workaround. The problem obviously lies in CyclesStreets which tries to be clever about inheriting names for unnamed ways from connected named ways. That stuff was written several years ago, hasn't been refined and is some way down the priority list.
