### ISSUE TITLE
"Find a Place" should zoom in

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#309]
At the moment, if you do "Find a Place" it centres the map on the location, but doesn't zoom in, so you then have to zoom in a bunch and "Find a Place" again.

I suggest it would be more intuitive to zoom at least to a minimum level - the user can always zoom out again at this point.

@mvl22 I think we should get this change into the 3.6 release; what are your thoughts?
(I noticed this while getting screenshots ready...)

**Comment by mvl22** [comment]
Yes, I ran into this with a new user yesterday. It's a clear usability failure and I was thoroughly confused by this too.

The Geocoder results each include a bbox of the feature that is returned:
https://www.cyclestreets.net/api/v2/geocoder/#example

The intended logic is thus that a find place should result in a zoom which fully contains that bbox as closely as possible (e.g. a search for Cambridge would zoom to contain Cambridge; a zoom for King's Parade would be zoomed in to that street), but that you should still set a sensible minimal zoom to ensure there is some context for small things like a single street (e.g. you do still want to see the streets around King's Parade).
