### ISSUE TITLE
Waypoint replanning doesn't work quite as intended

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#323]
Follows on from #106 and its related PRs.

### The intention:
-  Keep whichever remaining *planned* waypoints are appropriate (i.e. the ones that have not yet been passed)
-  Add a starting waypoint of current location.

### The problem:
-  This works fine if *after the first replan, you get right back on track*.
-  If you don't, then *subsequent replans include the location of the last replan as an additional waypoint*.  This is bad, as the route goes more and more mental as you try to shortcut towards the last intentional waypoint!

### Screenshot of the problem:
<img src="https://user-images.githubusercontent.com/6017680/45080706-6b602180-b0ed-11e8-8b24-f4afda9ed482.png" data-canonical-src="https://user-images.githubusercontent.com/6017680/45080706-6b602180-b0ed-11e8-8b24-f4afda9ed482.png" width="320" height="580" />)

### The proposed solution:
-  Define a type for waypoints - planned, or ad-hoc.  Ad-hoc ones are only generated by on-the-fly replanning, and *are not kept in any subsequent replans*.

**Comment by mvl22** [comment]
You can see why we had a limit of 12 now - the other app had a similar problem :)

**Comment by oliverlockwood** [comment]
Haha :-)
Fix is on the way, just getting the unit tests for it sorted.

**Comment by oliverlockwood** [comment]
@mvl22 PR to fix this is now raised.  With the potential impact in mind, do keep an eye on your server logs.  If we end up with some mad replanning with too many waypoints, we can contemplate getting a patch release out potentially including just this fix, instead of waiting for the next full release including other changes.  Let me know if this is needed.

**Comment by mvl22** [comment]
Sure.

I suggest we just aim for another release at the start of next week anyway, to include all the fixes this week. There’s no problem with issuing point releases - I’d rather get improvements and fixes out to users in smaller, stable releases than big releases that roll up large amounts of stuff and take a long time to appear, giving the impression of an inactive project.
