### ISSUE TITLE
Show date on photos

### ISSUE THREAD

**Issue by patrickvale** [cyclestreets/android#354]
When I use the photo map to check out potential obstructions/closures en route (for a big cargo bike) I don't see the date the photo was added anywhere on the Android photo map pop up which displays the picture.
Is there a way to find it?
I'm feeling it would be useful as some things may be quite date dependent like road works.

**Comment by oliverlockwood** [comment]
@patrickvale this seems like a reasonable request.

I haven't at the moment got much time for personal dev projects, but it looks like this would be possible without too much information - do you fancy submitting a PR?

Some pointers:
- API documentation - https://www.cyclestreets.net/api/v2/photomap.locations/#fields it looks like the `datetime` field is supported
- https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/V2Api.java#L43-L47 is where this API is consumed in the application (in turn used by https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/client/RetrofitApiClient.java and https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.kt)
- https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/Photo.java is the relevant domain object
- https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/java/net/cyclestreets/DisplayPhoto.java is where this is displayed to the UI
- https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/layout/showphoto.xml is the relevant layout XML.

If you (or anyone else reading this) is up for doing the development here, I'm happy to support, advise, and review PRs.

**Comment by patrickvale** [comment]
Thanks @oliverlockwood I will look into updating the application and submitting a PR.

**Comment by oliverlockwood** [comment]
Closed by #356.  Available to beta testers in the next day or two, and will be in release 3.7.
