### ISSUE TITLE
Google APIs: must target >= SDK version 28

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#361]
Currently, publication of the `master` build fails as follows:

```
Execution failed for task ':cyclestreets.app:publishReleaseApk'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$Processor
   > There was a failure while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$ApkUploader
         > 403 Forbidden
           {
             "code" : 403,
             "errors" : [ {
               "domain" : "androidpublisher",
               "message" : "Your app currently targets API level 26 and must target at least API level 28.",
               "reason" : "apkNotificationMessageKeyTargetSdkVersionTooLow"
             } ],
             "message" : "Your app currently targets API level 26 and must target at least API level 28."
           }
```

The fix for these seems pretty obvious; however, there will likely be some code change requirements as a result of this, so I'm raising a ticket to track.

**Comment by mvl22** [comment]
Does this mean that Google are only allowing Android 9 support now in app submission?

**Comment by oliverlockwood** [comment]
No, it's not a requirement on the **minimum** SDK version, it's a requirement on the **target** SDK version.

So we're going to have to deal with:
- https://developer.android.com/about/versions/pie/android-9.0-changes-28

**Comment by andrewshadura** [comment]
The branch can probably dropped since it’s been merged already.

**Comment by oliverlockwood** [comment]
Indeed, good spot @andrewshadura.
