### ISSUE TITLE
Waypointing has become a bit of an "art"... and the icons have become tiny

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#363]
This is a screenshot from my phone (Pixel 2).

I did my damndest to put a waypoint on the junction between Church Street and High Street / The Broadway.  It didn't go so well location wise, and the icon is smaller than it used to be.

![issue-waypointing](https://user-images.githubusercontent.com/6017680/79603844-f89a9300-80e4-11ea-83ef-b26d7b7df3fd.jpeg)

I suspect that the size, at least, is likely because the wisps are in the density-independent drawable folder (something which `lint` has been complaining about for ages) and I have a higher resolution on this phone than the previous.  So a starting point will be to fix that, and see if it makes a difference to the locations or not.

@mvl22 @jezhiggins where did the wisps originally come from?   (I'm talking about e.g. https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/drawable/green_wisp.png)
If we have some higher-resolution versions of these and/or scalable vector representations, that would be helpful.

**Comment by mvl22** [comment]
Paging @si-the-pie who made the wisps. Simon, can you fish out the originals and resave as SVG?

**Comment by si-the-pie** [comment]
Yes, I'll fish them out and place them as requested. Here's some notes about them.

Wisps are available as svg, here are the links:

https://www.cyclestreets.net/images/itinerarymarkers/start.svg

Replace `start` in the above with these values:

| name | color|
|-|-|
| start | green|
| waypoint | amber |
| finish | red |
| selected | blue |
| temporary | grey |
| wisp | purple |
| wisp_shadow | Intended to be a shadow |

In a browser setting these wisps are used as follows, using the `nearestpoint` api. When the user clicks it immediately plants the temporary grey wisp at the click point and calls `nearestpoint`. That resolves into a real waypoint often at a very nearby location and the temporary wisp is then replaced with a green, amber or red wisp depending on whether it is at the start, middle or finish of the route. The blue selected wisp is for when the mouse hovers and dragging. The purple one is unused at the moment.

The wisps were based on the `street` part of the CycleStreets icon and rotated 90° but were considerably fattened.

These svg files are in fact very small files:

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 51 99">
  <defs>
      <linearGradient id="shiny" x1="0.2" x2="0" y1="0" y2="1">
        <stop offset="35%" stop-color="limegreen"/>
        <stop offset="90%" stop-color="black"/>
      </linearGradient>
    <style>
      path.wisp {stroke:black; stroke-width:5; stroke-linejoin:round; fill:url(#shiny);}
    </style>
  </defs>
  <path class="wisp"
        d="M 13,3
           c -30,60   25,50   13,94
              25,-25 -20,-40  22,-86
             -15,8   -30,12  -34,-8 Z" />
</svg>
```
They scale beautifully, but you have to say how big you want them to be, this is done in html via a width or height properties on the element:

```html
<img src="https://www.cyclestreets.net/images/itinerarymarkers/start.svg" width="20"/>
```
<img src="https://www.cyclestreets.net/images/itinerarymarkers/start.svg" width="20"/>

```html
<img src="https://www.cyclestreets.net/images/itinerarymarkers/finish.svg" height="70"/>
```
<img src="https://www.cyclestreets.net/images/itinerarymarkers/finish.svg" height="70"/>

```html
<img src="https://www.cyclestreets.net/images/itinerarymarkers/waypoint.svg" width="100" height="100"/>
```
<img src="https://www.cyclestreets.net/images/itinerarymarkers/waypoint.svg" width="100" height="100"/>

**Comment by oliverlockwood** [comment]
Thank you @si-the-pie, I should be able to work with that.

I don't suppose you're able to provide similar for the direction icons?  e.g. https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/drawable/bear_right.png or https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/drawable/turn_left.png, and so forth?

**Comment by si-the-pie** [comment]
@oliverlockwood we don't have svg versions of those icons, so one of us would have to create them.

Creating them isn't too hard actually, all you have to do is work out the svg path for the arrow head and get it into a nice style and then just move the head around for each of the different turns. I'm tempted to have a go as it can be quite a fun distraction - but it would take a day or two.

**Comment by oliverlockwood** [comment]
@si-the-pie a day or two is fine, I'd really appreciate it if you could do that.

Please do include the additional ones that I slightly painstakingly created a couple of years ago to improve navigation at staggered-crossroads etc, e.g.:
- https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/drawable/bear_left_then_right.png
- https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-view/src/main/res/drawable/turn_right_then_left.png

**Comment by si-the-pie** [comment]
What do you think of these? They are created partially algorithmically so fairly easy to change.

<img src="https://www.cyclestreets.net/images/turnarrows/sharp_left.svg" width="40"/>
<img src="https://www.cyclestreets.net/images/turnarrows/turn_left.svg" width="40"/>
<img src="https://www.cyclestreets.net/images/turnarrows/bear_left.svg" width="40"/>
<img src="https://www.cyclestreets.net/images/turnarrows/straight_on.svg" width="40"/>
<img src="https://www.cyclestreets.net/images/turnarrows/bear_right.svg" width="40"/>
<img src="https://www.cyclestreets.net/images/turnarrows/turn_right.svg" width="40"/>
<img src="https://www.cyclestreets.net/images/turnarrows/sharp_right.svg" width="40"/>


```html
<img src="https://www.cyclestreets.net/images/turnarrows/straight_on.svg" width="40"/>
```

**Comment by mvl22** [comment]
Yes, they have a very nice character.

But I think the first and last are slightly unsatisfactory and unclear because the arrowhead laps with its tail.

**Comment by si-the-pie** [comment]
I've just uploaded new version the turn arrows, changed a bit since the ones I shared earlier.

Do you also need the four or five ones to do with roundabouts? They are a bit more complex!

**Comment by oliverlockwood** [comment]
@si-the-pie for future reference, although the contribution is very helpful indeed, please don't commit SVG files where you have been doing so, as it breaks the build (see my notes on PR #365).
You can put things in the `/assets` folder in the root instead 😃 

My thoughts:
* I like the style.
* In my opinion, the plain turn instructions e.g. "bear left", "sharp right", "turn left" ones look like they're not starting "straight", which I think is a little unhelpful.  These could be improved by moving the base point off-centre (it is off-centre for e.g. bear_left_than_right, which I think looks much better.)
* yes, I'm afraid the "first exit", "second exit" and "third exit" icons are required.  The "roundabout" one, however, is not, as we always join together "Enter roundabout" instructions with the exit information, otherwise, while doing a LiveRide, it would be easy to not be told your exit until you've already passed it!

**Comment by si-the-pie** [comment]
@oliverlockwood - next time I shall use the assets folder as directed.

- Glad you like the style.
- I hear your comments about the not starting straight. I did them like that because I wanted to capture a bit of the flow of cycling in that a turn left starts with a small wiggle to the right. Maybe that does look a bit over-fussy so I shall do another iteration without the wiggle.
- I'll create new versions of the three roundabout exit as required. However I'm a little wary of using such prescriptive images as for instance the second exit of a three legged roundabout is sometimes a right turn rather than always a straight on.

**Comment by si-the-pie** [comment]
New versions of the turn arrows with the straighter and offset stems have been added. I've also done a left hand version of the `double_back`, in case it's ever needed and renamed the existing one with the `_right` suffix. The roundabouts were surprisingly easy to do once I grokked the svg elliptic arc curve directive. I went for an infilled roundabout as I thought that looked much stronger.

**Comment by oliverlockwood** [comment]
They look great @si-the-pie, thanks for those.

I've created another ticket #366 to track making use of those icons, so I can keep the more urgent bug fix scoped to here.
