### ISSUE TITLE
Pressing "back" into the Settings window causes weird transparent overlay

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#364]
See screenshot, taken on my phone:

![issue-settings-overlay](https://user-images.githubusercontent.com/6017680/79605129-46b09600-80e7-11ea-8123-aa46c68a5085.jpeg)

Also reported by a user at https://play.google.com/apps/publish?account=7698300952134656507#ReviewDetailsPlace:p=net.cyclestreets&reviewid=gp:AOqpTOGjBMNC2vKaxCS0fmlRAt9YMB39sajnCHCw84fHH1NmBWJhNBL2RwCXNgiZiT8ltq5BXA3630KkjXx4uw

I believe this came in with the major menu updates that I did in 3.6.  I remember seeing it occasionally but I ran out of time to investigate.
We should fix in 3.7.

**Comment by mvl22** [comment]
Ooh, that is odd!

**Comment by oliverlockwood** [comment]
@jezhiggins to clarify the repro scenario: go into Settings, go into a sub menu such as LiveRide, use nav menu to go to e.g. Add Photo, click Back.

**Comment by oliverlockwood** [comment]
Resolved by #369.
