### ISSUE TITLE
Use new vector images for directions

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#366]
Follows on from #363, alongside with @si-the-pie was kind enough to upload a bunch of vector assets for our direction arrows etc.  These can be found in the `/assets/directions` folder of the repo.

This ticket covers making use of those in the codebase and removing the old density-independent bitmaps.

**Comment by si-the-pie** [comment]
Actually it occurs to me that you might need three more roundabout images for regions where they go around in the opposite direction. It'd be easier to do those now while the procedure is fresh in my mind.

**Comment by oliverlockwood** [comment]
That's very advanced... We'd have to make sure we coded for that :-)
