### ISSUE TITLE
Blank screen on load (after upgrading to AndroidX / Jetpack)

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#398]
After you first start the app following upgrade, you get a blank screen after closing the "What's New" page.

<img src="https://user-images.githubusercontent.com/6017680/81735493-085f8a00-948d-11ea-8077-a54cbcc7635b.jpeg" width=350>

The navigation menu can get you to the Journey Planner without any problems, but it's a bit of a crap experience. This does not repeat on subsequent loads of the app (until the next build is deployed, of course...)

@jezhiggins would you mind taking a look at this one?

**Comment by oliverlockwood** [comment]
I've just downloaded the latest version of the app to my phone, and this definitely happened.  It's a bit of a crap experience.

**Comment by mvl22** [comment]
Yes, I got exactly the same upgrading the beta just now. It is indeed rather odd.

**Comment by oliverlockwood** [comment]
Closed by #406.
