### ISSUE TITLE
Update icon set for POIs and Photomap

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#402]
See conversation on #312 for context.

**Comment by oliverlockwood** [comment]
POI icons have now been upgraded by #403.  These are actually derived from what's returned to us over the REST API; in this PR I changed our code to request 64x64 icons instead of 32x32, but so as to still display them at the same size on the screen (thereby we have just improved the resolution of these).
 
No work was done to improve the Photomap icons, and these still look a bit blurry.  I'll see what we can do about this in due course.

**Comment by mvl22** [comment]
Just to flag up that the Photomap API also returns icons, as SVG, and ideally you would therefore just use the `iconUrl` field for those, caching the path, rather than using hard-coded ones in the app distribution.

**Comment by oliverlockwood** [comment]
@mvl22 thanks.  I'm not sure whether Android will cope with downloading and then rendering an SVG though.  If you import a vector asset into your drawable folder Android will convert it from SVG to its own vector-representation XML (which is what we've done with the direction arrows etc.)

So we may end up with a choice between:
- embedding vector images in the distribution
- downloading and using PNGs

**Comment by mvl22** [comment]
Please embed then.

**Comment by mvl22** [comment]
The icons appear very large on a Motorola G6 Play:

![Screenshot_20200519-144629](https://user-images.githubusercontent.com/361423/82843260-892e7500-9ed4-11ea-837e-b056f51d3b04.png)

**Comment by oliverlockwood** [comment]
hmm, I'll try specifically getting an emulator of that device, and will see what's going on.

**Comment by oliverlockwood** [comment]
@mvl22 what version of Android is running on this?  perhaps you can screenshot the phone's info screen or similar?

**Comment by oliverlockwood** [comment]
While I'm waiting for feedback on the above issue, I've been experimenting with the vector graphics for Photomap icons.
Here's a couple of screenshots.  In both, I'm only using vector graphics for the "cycleways - neutral" image.

In the first, I've worked to get the icons as close to the same size as possible (by setting the drawable height to 17dp).

In the second, I've offered an alternative size (height 21dp - a nicely scaled half; the proportions of the original vector definition are 38w x 42h).

<img width="433" alt="Screen Shot 2020-05-29 at 20 36 29" src="https://user-images.githubusercontent.com/6017680/83298442-5e9e2e00-a1ec-11ea-91fb-0a202c6adbd1.png">
<img width="433" alt="Screen Shot 2020-05-29 at 20 37 23" src="https://user-images.githubusercontent.com/6017680/83298458-64940f00-a1ec-11ea-9bd8-72ff9b795532.png">

In both cases the vector graphics are clearly crisper, as expected.
In my view the slightly larger form is better (I've always thought the photomap icons a bit small), but I'll happily be guided by the opinions of others.

@mvl22, @HilaryN, @jezhiggins, @si-the-pie - your thoughts please?
(In terms of importing the vector graphics, Android wants you to specify the default scaling at the time of importing SVG into Android vector XML, so it's easier to get the decision right up front than after the fact.)

**Comment by HilaryN** [comment]
I like the second one - they are much clearer.

**Comment by oliverlockwood** [comment]
@mvl22 this issue now only remains open for the point raised by Martin:
>The icons appear very large on a Motorola G6 Play:

<img src="https://user-images.githubusercontent.com/361423/82843260-892e7500-9ed4-11ea-837e-b056f51d3b04.png" width=330>

From https://www.gsmarena.com/motorola_moto_g6_play-9002.php I gather that:
- Screen is 5.7 inches, 83.8 cm2
- Resolution is 720 x 1440 pixels, 18:9 ratio (~282 ppi density)

In the absence of further information.  I've assumed this is running Android Pie (API 28).
By using the above icons I can reproduce this in the emulator; interestingly, the new Photomap icons look to be an OK scale.

For context, the new Photomap icons are 17dp high (as discussed here and in the related PR #412).
The POI icons used to be 32 pixels, turned into a BitmapDrawable with no scaling.
I had intended my change just to double the density (using the 64px icons without changing the size).  However with a little experimentation on different screens it is clear that the scaling of these for different screen densities is not working as intended.  I will revisit.

**Comment by mvl22** [comment]
Yes, it’s Android 9.

**Comment by oliverlockwood** [comment]
Probably we can get reasonable scaling by just including the 64x64 icons in the xxxhdpi folder, and the 32x32 icons in the xhdpi folder, giving us 16dp (as close as is reasonble) to the 17dp Photomap icons.  Obviously updates to icons will require updates to the app, but we've already made that compromise for improved graphics on the Photomap icons, and I think it's probably the right tradeoff here too.
