### ISSUE TITLE
Hitting "Saved locations" in Settings crashes the app

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#404]
I think this is probably my fault, likely introduced by #403.  Anyway, I'll fix it.

**Comment by jezhiggins** [comment]
Confounder -> I did go to this screen while looking at #403, but didn't have a problem.

**Comment by oliverlockwood** [comment]
Intriguing 😬 

I'll see if it repros on the emulator; otherwise it might be time to plug my phone in and capture the logs from there.  Because it's happening pretty reliably for me.

**Comment by oliverlockwood** [comment]
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter convertView
  at net.cyclestreets.LocationsFragment$LocationsAdapter.getView(Unknown Source:2)
  at android.widget.AbsListView.obtainView(AbsListView.java:2405)
```

![WhatsApp Image 2020-05-19 at 20 03 18 (2)](https://user-images.githubusercontent.com/6017680/82367678-1755b780-9a0c-11ea-863e-b3b094aababc.jpeg)

![WhatsApp Image 2020-05-19 at 20 03 18](https://user-images.githubusercontent.com/6017680/82367583-f8572580-9a0b-11ea-9277-1233d3d0914e.jpeg)

Copied from the Send Feedback dialog on my phone (hopefully Martin will pass on the email in due course, but this lets me get started, as the situation does not repro in the emulator).

**Comment by oliverlockwood** [comment]
And I've figured out the fix (I believe).  PR ready for review @jezhiggins.
