### ISSUE TITLE
Exiting LiveRide shows last instruction instead of journey details

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#409]
When exiting LiveRide before the end of the journey (using back button) the last instruction shows instead of the journey details.  Shown here in Pixel 3 XL emulator:

<img width="957" alt="Exit live ride shows last instruction" src="https://user-images.githubusercontent.com/59799824/82741259-3b850180-9d48-11ea-9e6d-551a93856981.PNG">

**Comment by oliverlockwood** [comment]
I think this is working as designed. You can use the arrows on the bottom left to move between different segments, long press to go all the way to start or end, and I think it's correct to persist the segment you were last looking at (or, in this case, riding).

**Comment by jezhiggins** [comment]
Designed is a strong word :), but yes this is intentional behaviour.

**Comment by HilaryN** [comment]
Ah OK, I didn't realise you could get back to the summary with a long press.
