### ISSUE TITLE
Up-front request for photo permissions 

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#411]
This dialog appears on first-run. It certainly appears rather intrusive.

Can we ensure that the photo permission is only requested at the point of wanting to add a photo? That is the only circumstance when that is required, and many users won't want to use the Photomap feature anyway.

![Screenshot_20200518-142929](https://user-images.githubusercontent.com/361423/82843732-fe4e7a00-9ed5-11ea-9e7a-67a3de01c84d.png)

**Comment by jezhiggins** [comment]
This isn't asking for permission to take a photo, it's asking for permission to use the filesystem. Filesystem access is all or nothing, if you have the filesystem permission you can read almost everything, hence "access photos, media and files". The reason we need this permission is to cache map tiles. If that permission was denied, we probably could operate (although I've never tried) but we'd constantly be hitting the network. 

We probably can delay asking so it doesn't overlay the splash screen, but we do need this permission and we do need it pretty promptly.

**Comment by oliverlockwood** [comment]
I consider this closed by #440.  We're still going to ask up-front for permissions, but it should now be a lot clearer _why_ we're asking.

**Comment by mvl22** [comment]
Can I just check why caching map tiles involves camera roll access?

We never want the map tile bitmaps to appear as photos - they’re just temporary memory.

**Comment by oliverlockwood** [comment]
@mvl22 please reread Jez's answer to this above. It's file system access, not specifically camera roll access.

**Comment by jezhiggins** [comment]
Yes, that's right - it's file system access - but the language of the permissions pop-up phrases it in terms of photos and files. The specific wording varies by some combination of device/Android version/vendor, but will always include a reference to photos.
