### ISSUE TITLE
Curious selection of POI types available to the app's API key

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#415]
One for @mvl22 & @si-the-pie, this.

If I hit the `poi.types` API using the app's API key, I get the following:
>['B&Bs', 'Beds for Cyclists', 'Bike shops', 'Bus stops', 'Cafes', 'Car sharing', 'Cashpoints (ATMs)', "Children's playgrounds", 'Cinemas', 'Convenience stores', 'Cycle parking', 'Drinking water', 'Hospitals', 'Libraries', 'London Cycle Hire points', 'Museums', 'Parks', 'Police stations', 'Postboxes', 'Public art', 'Pubs', 'Railway stations', 'Recycling', 'Restaurants', 'Schools', 'Supermarkets', 'Taxi ranks', 'Telephones', 'Theatres', 'Toilets', 'Tourist attractions', 'Tracks', 'Winter grit bins', 'Worship, place of', 'Youth hostels']

If I hit it with a different API key, I get the following:
>['Archaeological sites', 'B&Bs', 'Bike repair stations', 'Bike shops', 'British Cycling clubs', 'Bus stops', 'Cafes', 'Cairns', 'Campsites', 'Car sharing', 'Cashpoints (ATMs)', 'Castles', "Children's playgrounds", 'Cinemas', 'Convenience stores', 'Cycle parking', 'Cycle sport', 'Drinking water', 'Gardens', 'Golf courses', 'Hospitals', 'Libraries', 'London Cycle Hire points', 'Museums', 'Nature reserves', 'Parks', 'Police stations', 'Postboxes', 'Public art', 'Pubs', 'Railway stations', 'Recycling', 'Restaurants', 'Roman roads', 'Ruins', 'Schools', 'Stone circles', 'Supermarkets', 'Table tennis tables', 'Taxi ranks', 'Telephones', 'Theatres', 'Toilets', 'Tourist attractions', 'Tourist information', 'Tracks', 'Viewpoints', 'Windmills', 'Winter grit bins', 'Worship, place of', 'Youth hostels', 'Zoos']

It strikes me that these lists might have evolves without considering what should be excluded/included for the app's specific API key.

The notable oddities are:
1. The following seem like candidates for possible removal:
   - Winter grit bins
   - Car sharing
   - Recycling
2. The following seem like they perhaps should be included:
   - Bike repair stations
   - Campsites
   - Cycle sport
   - Tourist information
   - Viewpoints

There are others that could be added/removed, but the above lists were my starting point.  What do you think?

**Comment by oliverlockwood** [comment]
@mvl22 any thoughts on this?

**Comment by mvl22** [comment]
I've adjusted this.

You can change this directly now. If you log in to the CycleStreets website, go to your profile (top-right name link), click on the API keys tab, go into the key for the app, then click on 'POI types'.

**Comment by oliverlockwood** [comment]
Thanks, I didn't realise we could change that ourselves.

Icons in the app now updated by commit: https://github.com/cyclestreets/android/commit/243a6f7e2e235de27c1054c1b09d5cd7cca0c70e

**Comment by oliverlockwood** [comment]
Moved this to 3.8.1 as it looks like the change to what the API returns means the app crashes when you open the POI menu.

I'll also make this more robust while we're at it.

**Comment by oliverlockwood** [comment]
@mvl22 no thanks. I have published release 3.8.1 which fixes this.

**Comment by mvl22** [comment]
Brill!
