### ISSUE TITLE
Android 10 (API level 29) targetSdkVersion by Nov 2, 2020

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#434]
Hello Google Play developer,

This is a reminder that starting November 2, 2020, updates to apps and games on Google Play will be required to target Android 10 (API level 29) or higher
https://support.google.com/googleplay/android-developer/answer/113469#targetsdk .  
After this date, the Play Console will prevent you from submitting new app bundles and APKs with a targetSdkVersion less than 29. Please note that Wear OS  
https://developer.android.com/training/wearables/apps/creating  
apps are not subject to the API level 29 requirement. This will not impact your existing listing on the Play Store.

Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion).

Action required

Please ensure that your apps are configured to target at least Android 10 (API level 29) by November 2, 2020. For technical advice on how to change your app's target API level to meet these requirements, refer to the migration guide:
https://developer.android.com/distribute/best-practices/develop/target-sdk .

Affected apps

The apps included below have one or more app bundles or APKs—in production or testing tracks—that aren't currently targeting API level 29 or higher. Apps are listed with the maximum version code and corresponding targetSdkVersion. If you have more than 20 apps that could be affected in your account, please check the Play Console for a full list.

- net.cyclestreets
- net.cyclestreets.maps.uk

**Comment by oliverlockwood** [comment]
@jezhiggins I'll take the main Cyclestreets app, perhaps you can deal with the map pack?
