### ISSUE TITLE
Jump through Google hoops for background location access etc.

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#439]
Once we've finished addressing #429, there'll be this to deal with:
https://support.google.com/googleplay/android-developer/answer/9799150

This includes among other things - I'm not joking - a requirement to publish a video showing how we use background permission.  Thanks a bunch, Google.

**Comment by oliverlockwood** [comment]
Realised this isn't necessary after all, because we keep the LiveRide as a foreground service (with a permanent notification).  See discussion in 429 and linked PRs.

**Comment by mvl22** [comment]
Good.

It's reassuring actually that Google are cracking down on that kind of stuff. Wonder if their own Google Maps engineers had to make a video, given the amount of user tracking that goes on there ;)

**Comment by oliverlockwood** [comment]
@mvl22 the same thought had occurred to me!
