### ISSUE TITLE
Latest Beta build doesn't download map tiles

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#450]
Maps just remain blank.

I think that's because we've upgrade to target SDK30 (Android 11): https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11
> If your app targets Android 11, both the WRITE_EXTERNAL_STORAGE permission and the WRITE_MEDIA_STORAGE privileged permission no longer provide any additional access.

We have the choice here to cache our tiles in an app-specific location, or to request "all files access".

I'm inclined to think we should do the former (which is what Google is encouraging, after all).

Any thoughts @HilaryN @jezhiggins  @mvl22 ?

**Comment by oliverlockwood** [comment]
weirdly it seems to work on the emulator - and the base path is logged like `/data/user/0/net.cyclestreets/files/osmdroid`, which is already app-scoped.

I don't know why it's not working on my phone - I guess I'll have to plug the debugger in and see what's up.

**Comment by HilaryN** [comment]
Is this in journey planner?

There's an issue in the location editor (Saved Locations in Settings) where if you pause and resume then the map tiles don't re-appear after resuming.  (In journey planner it re-initialises CycleMapView and the fragments after resuming so the map tiles get re-loaded.)

I've been doing quite a bit of testing on Android 11 emulator (Pixel 2 API 30) and not had an issue except the above.

**Comment by oliverlockwood** [comment]
I can't seem to reproduce this, despite experimenting with an emulator in various versions with various versions of our software.  Closing.

**Comment by oliverlockwood** [comment]
Looks like I should have spent more time on this. #461 is clearly a user hitting the same thing.
