### ISSUE TITLE
"Ask every time" permission doesn't work after denying twice

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#451]
On Android 11, if you deny location permission twice then go to settings and set permission to "Ask every time", the app thinks permission is still denied and LiveRide / Current location won't work.

I know it's a minor issue, but while it was fresh in my mind I thought I'd fix it.

PR coming soon. :-)

**Comment by mvl22** [comment]
Sounds like this can be closed, once it has been merged in? I see Jez has reviewed.

**Comment by HilaryN** [comment]
Merged.
