### ISSUE TITLE
Have to tap LiveRide button again after granting location permission

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#452]
If you tap the LiveRide or location button and the permission request comes up, and you grant permission, you then have to tap the LiveRide or location button again for it to work.

Probably affects me more than the average user as I am frequently reinstalling, but I thought I'd fix it for a better (new) user experience :-)

PR coming up...

**Comment by mvl22** [comment]
Sounds like this can be closed, once it has been merged in? I see Jez has reviewed.

**Comment by HilaryN** [comment]
Merged.
