### ISSUE TITLE
Android 11 regression in version 3.9

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#461]
User feedback:

> The app doesn't load maps for me (android version 11, pixel phone) after the latest update. If I zoom in really close a section of the map might load but as soon as I zoom out a tiny bit only the line shows against a background of grey squares.
Thanks for a lovely app before that!

Sounds like tiles aren't loading. Could there be a write permission error perhaps?

**Comment by oliverlockwood** [comment]
Whoops. I'll try to repro tomorrow.

**Comment by oliverlockwood** [comment]
@mvl22 this should now be resolved in the new release 3.9.1.

Perhaps tomorrow morning (once the play store has had time to deal with the rollout) you could ask the person who raised the issue to download the new version and feed back.

**Comment by mvl22** [comment]
Brilliant - thanks; will do.

**Comment by oliverlockwood** [comment]
@mvl22 any feedback yet?

**Comment by mvl22** [comment]
Not yet; I responded to their feedback yesterday late afternoon. People sometimes can take a few days to respond, if they do at all.
