### ISSUE TITLE
Server: "Too short" error message for leisure routing doesn't appear as presumably intended

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#464]
If you hit http://www.cyclestreets.net/api/journey.json?key=redacted&plan=leisure&itinerarypoints=0.125325,52.219285&distance=30&reporterrors=1

the error message that comes back is:
```json
{
  "error": "Too short: journeys must be longer than 4 metres. (Your requested journey was  metres)."
}
```

It looks to me like the server is failing to pass back the requested distance value in this error message.

**Comment by mvl22** [comment]
Thanks, Simon will hopefully look at this.

PS I noticed this has an HTTP URL rather than HTTPS. Can you switch to HTTPS if possible? I can start a new issue on this if you can confirm.

**Comment by oliverlockwood** [comment]
That was just me manually testing in a browser, don't worry about it being HTTP.

**Comment by si-the-pie** [comment]
In leisure routes four waypoints are created to give an overall total estimate distance that matches the `distance` parameter which is only 30 metres in this case. In this case all four waypoints have resolved to the same point and hence it comes up with a distance of zero. I think the thing to do is to create a message specially for leisure routes to suggest that something a bit more ambitious should be tried.

**Comment by oliverlockwood** [comment]
I don't really mind how you decide to change this; it's unlikely to be hit in the app as we enforce a minimum distance anyway. But I thought you would want to know :-)

**Comment by si-the-pie** [comment]
Yes, I'm very grateful for the report, thank you. Good idea to have a minimum distance for a leisure routes - what value have you chosen?

There should also be a minimum duration as that gets converted into a distance according to the formula: `distance = 0.278 * speed * duration` where 0.278 converts km per hour to metres per second, speed is the desired speed (defaulting to 16kmph), and the duration is in seconds.

I notice in the code the minimum values for distance and duration are 1 metre and 12 seconds, which are obviously stupid! It would make more sense to be say 30 minutes, which converts nicely to around 8km / 5 miles.

**Comment by mvl22** [comment]
> I notice in the code

I presume you meant the API server code.

**Comment by oliverlockwood** [comment]
@si-the-pie at present the minimum in the app is 5 mins, 1km or 1 mile (the latter depending on the units you have set in the app).

However this is only in beta, I'd be happy to adjust it.  But perhaps smaller minima should be considered than your suggestion above, e.g. for people with young kids.
(slight brag: my 4-and-a-half-year-old managed 11 miles in one go last week, but I can still imagine it being realistic for people to look for 2-3km routes?)

**Comment by si-the-pie** [comment]
The API was updated at 7pm this evening to enforce a minimum duration of 300 seconds and a minimum distance of 1000m.

See https://www.cyclestreets.net/api/v1/leisure/#leisureParameters which now shows the mininum values, whereas it did not before.

**Comment by oliverlockwood** [comment]
In theory this sounds good to me.

Now when I hit the API with e.g. `distance=30` it comes back with
> "The distance parameter must be at least: 1000."

**However**, if I hit it with e.g. `duration=200` it **still** comes back with the same error message (note: I am not specifying distance in this case).  This is surely incorrect.

Interestingly it accepts `duration=250` and generates me a route, which doesn't mesh up with the minimum 300 you described in your previous comment.

Your thoughts, @si-the-pie ?

**Comment by si-the-pie** [comment]
> Your thoughts, @si-the-pie ?

It was a lack of sufficient testing on my part, apologies for my sloppiness there.

Fixes have been applied, but even better, new tests have been added for the cases where either the duration or the distance values are too small or whether either of the parameters are missing. All of these tests are currently passing and so I hope this does not cause continued frustration there.

**Comment by oliverlockwood** [comment]
Looks good to me now.  Thanks for fixing @si-the-pie .
