### ISSUE TITLE
Add POIs option to Circular Route screen

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#465]
(I've started on this.)

**Comment by HilaryN** [comment]
A couple of observations:

3 POI's are returned for a leisure route even if none requested.  (Some interesting-looking categories, e.g. naturereserves, carshare, which aren't included in the list of categories?) e.g.:

https://www.cyclestreets.net/api/journey.json?plan=leisure&itinerarypoints=0.0020170211791992188%2C51.46275083133955&duration=4260&reporterrors=1&key=

Should I display those, do you think?

When I request a circular route with POI's it seems to always return 3 POI's. (I tried with different journey lengths.)  Is that deliberate / what you'd expect?  e.g.

https://www.cyclestreets.net/api/journey.json?plan=leisure&itinerarypoints=-0.005321502685546875%2C51.44705336128538&duration=4380&poitypes=bikeshops%2Ccafes&reporterrors=1&key=

**Comment by oliverlockwood** [comment]
I'd ask for the opinion of @mvl22 and @si-the-pie

**Comment by HilaryN** [comment]
@mvl22 and @si-the-pie? (Nudge)

**Comment by mvl22** [comment]
Ideally we wouldn't be showing POIs if the user hasn't requested them. Though it's not harmful as such - up to you really whatever you think is best.

I'll add an upstream ticket that we shouldn't be showing these. So it's probably best for you just to render whatever comes back from the API, and at some point this will stop showing stuff that shouldn't be there.

**Comment by si-the-pie** [comment]
Allow for the POIs to disappear unless explicitly requested, as might happen when the issue is eventually addressed.

**Comment by HilaryN** [comment]
Thanks, both.
