### ISSUE TITLE
Circular routes has stopped working

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#466]
https://www.cyclestreets.net/api/journey.json?plan=leisure&itinerarypoints=0.03201484680175781%2C51.46852571389458&distance=25000&duration=0&poitypes=atms&reporterrors=1&key=...

gives error message "Parameter duration is not a naturalNumber."

Removing the duration parameter returns the route OK:
https://www.cyclestreets.net/api/journey.json?plan=leisure&itinerarypoints=0.03201484680175781%2C51.46852571389458&distance=25000&poitypes=atms&reporterrors=1&key=...

Has something changed in the API?

**Comment by mvl22** [comment]
Don’t think so, but in that first request you’re sending both a distance and a duration, and the latter as zero.

**Comment by si-the-pie** [comment]
Actually the API was updated at 7pm this evening to enforce a minimum duration of 300 seconds and a minimum distance of 1000m. See https://www.cyclestreets.net/api/v1/leisure/#leisureParameters which now shows the mininum values, whereas it did not before.

I was taught that Natural Numbers are the integers starting from 1, but I realise this not widely accepted so the error message will change eventually to something a bit clearer.

**Comment by HilaryN** [comment]
I think when I was first experimenting with the API I tried passing 0 for the parm not being use, expecting it to be rejected and then I was going to change it to null.
But it worked with 0, so I left it.
Changing it to null now...

**Comment by mvl22** [comment]
Please don’t send parameters that are empty - just ensure the logic is constructed so non-required values are not sent at all. It’s ambiguous if the API receives both when only one is intended.
