### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#468]
On the latest beta release the app just crashes on load. Clearly I should have run it on the emulator after the plugin upgrades - apologies. I will fix ASAP.

**Comment by HilaryN** [comment]
This still isn't working for me.  I pulled in the changes and it seems to build OK, but doesn't start up in the emulator.  In logcat it says:
2021-04-14 14:52:30.751 2580-3208/com.google.android.gms.persistent W/GLSUser: [AppCertManager] IOException while requesting key: 
    java.io.IOException: Invalid device key response.

**Comment by oliverlockwood** [comment]
After updating to today's build, it works fine on my phone (Pixel 4a, Android 11) What version of Android are you running in the emulator, and have you definitely got today's release? (ie what's on master at the moment)

**Comment by HilaryN** [comment]
Yes, definitely got latest commits.
I've found I needed to actually uninstall the previous version for it to work, which I don't normally need to do.
Similarly on my phone I have had to uninstall it and re-download from the Playstore for it to work.

**Comment by oliverlockwood** [comment]
@HilaryN perhaps you could tell me exactly the details of your phone and emulator, so I can investigate it so hopefully other beta users don't have to go through that

**Comment by jezhiggins** [comment]
Build 3.10.0/1626 is working for me on a OnePlus 5 running Oxygen 10. 0.16, which is a roundabout way of saying Android 10.I have no way of knowing if this is helpful, but I hope so. 🤞On 14 Apr 2021 21:23, Oliver Lockwood ***@***.***> wrote:
@HilaryN perhaps you could tell me exactly the details of your phone and emulator, so I can investigate it so hopefully other beta users don't have to go through that

**Comment by HilaryN** [comment]
Phone is Fairphone 3, Android 10.

Emulator, Pixel 2 API 28.  Just checking other emulators as I think it was the same with Nexus 6 API 29.

**Comment by HilaryN** [comment]
Same with Nexus 6 API 29 but maybe it's just something with the setup I have in Android Studio.
Maybe if I'd waited for my phone to update from the Playstore it would have been OK.

**Comment by HilaryN** [comment]
Yes, it just seems to be that it won't reinstall over the version which is already there when I try and run it from Android Studio.  Though if I go back to an older branch it does reinstall, so it does seem to be related to the changes.  I'll try and work it out.

**Comment by HilaryN** [comment]
What version of Java should I be on now?  I don't seem to be able to download 9 - is 15 OK?

**Comment by oliverlockwood** [comment]
I would use 11

**Comment by HilaryN** [comment]
Thanks - that's sorted the problem :-)
