### ISSUE TITLE
Don't save route replans

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#474]
If you take a diversion and the app replans your journey, don't save it in the route history. It's annoying especially when you end up with multiple replans.

**Comment by HilaryN** [comment]
I'm sure you know the app inside out, but I keep coming across functionality I previously had no idea about when I'm looking through code.
Recently I saw you can tap and hold to delete or rename saved routes, which I'm finding quite handy.

**Comment by oliverlockwood** [comment]
One thing that I've been thinking is to have a "tutorial / tips mode" that defaults on for new installs, can be turned off via a "don't show tips like this" button, and can also be enabled /disabled in Settings.

We occasionally get negative reviews for things like this, where people haven't worked out how to do something. Of course, ideally it'd just "be intuitive" but there we are.

I've been meaning to raise an issue about both the above, and also that it would be nice to be able to bulk-delete routes if desired. So maybe a long-tap to start selecting, the ability to then tap more to add / remove selections, and then an option to delete (probably with confirmation dialog). Do you fancy raising tickets for these (if you agree with the idea)?

**Comment by HilaryN** [comment]
Good idea.  I was thinking videos on the website, but this would be good.
