### ISSUE TITLE
Use current route type for replan

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#476]
When re-planning a route from LiveRide, use the current route type rather than the one in settings.
e.g. I might have "balanced" as preferred type in my settings, but I might decide I want to use the fastest route when riding a particular route.  If I go off route then I'd like the replan to continue to be the fastest route rather than changing it to balanced.

**Comment by oliverlockwood** [comment]
Good call 👍

**Comment by HilaryN** [comment]
(Temporary workaround is to remember to change the route type in settings before setting off.)

**Comment by HilaryN** [comment]
Just doing this now.

In the event that the current route is a leisure/circular one, the replan changes to a linear route.  I was going to use the route type from settings in this case, but it doesn't seem appropriate to replan a leisure route as Fastest if that's what's in the settings, so I will ignore the settings and always replan circular routes as Quietest.

@mvl22 do you think this is appropriate?  Or should I do a circular route replan as Balanced?

**Comment by oliverlockwood** [comment]
My two pence: I think a circular route replan should be Balanced. "Quietest" has a really tedious tendency to take footpaths and make me get off and walk.  I never use it.

**Comment by mvl22** [comment]
> My two pence: I think a circular route replan should be Balanced. "Quietest" has a really tedious tendency to take footpaths and make me get off and walk. I never use it.

The leisure routing uses the quiet route internally, so I believe that should be used. I don't think the balanced route is often suitable for the idea of a leisure route.

We are aware of some ongoing issues about long dismounted sections, but I'd rather we tried to get those resolved. Oliver, if you could plan some examples and give feedback, that would be really helpful. In general, dismounted sections tend to happen when there are few other choices, i.e. the physical road/street/path infrastructure in the area is poor and thus there is little choice for someone who doesn't want to go on busier roads. However, we do know the engine isn't always quite right, so example cases are useful.
