### ISSUE TITLE
POI link not working in Android 11

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#508]
Recommended course of action is to put a try/catch around the StartActivity when launching the URL:
https://stackoverflow.com/questions/71443029/android-11-resolveactivity

https://developer.android.com/training/package-visibility/use-cases

I'll do this.

**Comment by mvl22** [comment]
Which link is this?

A POI may or may not have a link, as not all locations have a website.

**Comment by jezhiggins** [comment]
This is for POIs that have a link. If they don't, then there's nothing to open so we don't even try 👍On 29 May 2022 10:32, Martin ***@***.***> wrote:
Which link is this?
A POI may or may not have a link, as not all locations have a website.

**Comment by HilaryN** [comment]
My phone has recently upgraded to Android 11.  I was trying to find a restaurant on Friday night and the links wouldn't work :-(
