### ISSUE TITLE
Show Alternative route distance and time

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#510]

**Comment by mvl22** [comment]
What’s an Alternative route?

The screenshot showing two different timings next to each other is rather confusing…

**Comment by HilaryN** [comment]
No it's not automatically-generated.  It's generated by the user.

Let's say you've plotted a route, but it goes through a park and it's night time so you don't want to go through the park (even supposing it's open!).  It's dangerous and you could get attacked.
Rather than having to replan the whole route and put your waypoints in all over again, you can now just tap on the screen to add extra waypoint(s) to avoid the park.  (See PR #505 )  The alternative route shows in a different colour and doesn't become the main route until you confirm.  This gives you the chance to compare the new route to the original route.

I'm finding this SUCH a time-saver in being able to fine-tune my routes.

But as well as viewing the alternative route before accepting it, it would be good to see the changed distance and time.

Would it be better to put the word "alt:" before the alternative distance and time as in the screenshot below?

![image](https://user-images.githubusercontent.com/59799824/186458658-6922d80e-ad26-4a7a-9805-b54dea30e0bd.png)

**Comment by mvl22** [comment]
Yes, that makes it much clearer!
