### ISSUE TITLE
Erroneous server errors: "Too long: journeys are limited to 300km."

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#513]
This started recently. Look at the screenshots attached.

@mvl22 please would you get this looked into urgently? I can't seem to plan *any* routes at present.

**Comment by oliverlockwood** [comment]
I'm an idiot. I obviously had an orphan waypoint away off screen. Sorry for the false alarm... It's been a long day.

**Comment by mvl22** [comment]
No worries :)
