### ISSUE TITLE
Footprints in Itinerary don't show

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#515]
The footprints, which indicate that a segment is a walking segment in the Itinerary, don't show unless a segment is selected, because they are white on a white background.  It would be nice to be able to see these even if a segment isn't selected.

![image](https://user-images.githubusercontent.com/59799824/187280730-8732a84c-1b16-4ec9-b4e5-aa02c6719aa0.png)

**Comment by HilaryN** [comment]
(I'm doing a fix alongside #497 )

**Comment by HilaryN** [comment]
I've fudged this to make all the itinerary steps show as walking, just to get an idea of how the footprints would look with different types of arrow:

![Screenshot_1662128482](https://user-images.githubusercontent.com/59799824/188170209-890aba04-0a68-4635-8b03-1c5277a66f19.png)

**Comment by mvl22** [comment]
I would strongly recommend not having different footprint positioning depending on the arrow. Visually this breaks standard design rules about consistency.

Basically just pick a location, e.g. bottom right of the square, and stick to it. If you set it to overlay the arrow with a higher z-index then it will always show and not be lost. Consider putting a white circle around the feet so that it is always visually separate over the arrow as a small blob.

**Comment by HilaryN** [comment]
The positioning here is the same for all the arrows - I just wanted to see how it would actually look with different arrows.

**Comment by oliverlockwood** [comment]
> The positioning here is the same for all the arrows - I just wanted to see how it would actually look with different arrows.

What I notice upon close inspection, is that the arrows have a clear background, and then the footprints have a white background.
This becomes obvious in the entries in the instructions which spill onto a second line.

In my opinion:
1. if there is to be a background, this should be part of the layout such that it is either there or not there, consistently for the whole relevant image area, regardless of whether there are footprints, and regardless of the length of the instruction line.
2. Both the arrow (as currently) and footprint images should have a clear background.
3. We would benefit from @si-the-pie's vector image drawing skills to define a footprints icon SVG which we can then import into an Android vector icon (we did this before, for all the arrows, and it made things look a *lot* better).
