### ISSUE TITLE
"Could not contact CycleStreets.net: Chain validation failed"

### ISSUE THREAD

**Issue by HilaryN** [cyclestreets/android#521]
Getting this message when trying to do a route in JourneyPlanner:
"Could not contact CycleStreets.net: Chain validation failed"

**Comment by jezhiggins** [comment]
It's possible this is a timezone thing. Has anything happened on the server send?(This might also account for the poi failures) On 31 Mar 2023 18:49, HilaryN ***@***.***> wrote:
Getting this message when trying to do a route in JourneyPlanner:
"Could not contact CycleStreets.net: Chain validation failed"

**Comment by HilaryN** [comment]
I tried in the emulator and on a different device and got the same issue.  Also rebooted and still had the issue. :-(

**Comment by HilaryN** [comment]
Ah no, sorry, on the device I rebooted it IS now working.  Must have got confused with all the different devices (and website, where it works fine).

**Comment by mvl22** [comment]
Just to confirm we’re running a pretty standard SSL config set to the Mozilla Intermediate template.

Android 4 and below will have issues due to older TLS being disabled but tbh I doubt many sites show at all with that old OS.

**Comment by HilaryN** [comment]
This was Fairphone 3 with Android 11, Fairphone 2 with Android 10, and the emulator in Android Studio was Pixel 4a API 31 (Android 12).
Now I've re-booted my (Windows) PC the emulator is working OK.
I've just tried it on the Nexus One API 29 emulator and it's fine, though not sure if that's because I've re-booted my PC.
