### ISSUE TITLE
Crash on starting a route

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#532]
User e-mail:

"I have tried to use your app on an android phone but it crashes when I try to start a tour. I can plan a tour but as soon as I start it crashes and returns to my home screen. I have deleted and re-installed the app and I have tried it on another android phone but I always get the same result."

Are we able to identify this crash from the Android reporting?

**Comment by jezhiggins** [comment]
Haven't been able to look at the crash luges yet, but pretty certain this confined to the new beta release. I'll investigate as soon as I'm ableOn 9 Aug 2023 17:39, Martin ***@***.***> wrote:
User e-mail:
"I have tried to use your app on an android phone but it crashes when I try to start a tour. I can plan a tour but as soon as I start it crashes and returns to my home screen. I have deleted and re-installed the app and I have tried it on another android phone but I always get the same result."
Are we able to identify this crash from the Android reporting?

**Comment by jezhiggins** [comment]
Confirmed - it's a breaking API change that's hit us because of the enforced move to API level 31. 

Will get new build out as quickly as I can.

**Comment by jezhiggins** [comment]
Patch build done and up on Google Play. Should be pushed out in the next few hours.

**Comment by mvl22** [comment]
> Patch build done and up on Google Play. Should be pushed out in the next few hours.

Thanks. Was this issue only on the beta channel or on main release?

**Comment by jezhiggins** [comment]
It was only on the beta channel
