### ISSUE TITLE
F'Droid release

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#536]
Just a reminder that the latest release needs to go on F'Droid too. We've had at least one user ask about this.

https://f-droid.org/packages/net.cyclestreets/

**Comment by jezhiggins** [comment]
All the FDroid releases were done by someone else - I don't know who - without reference to us. I will look at what the mechanism is, but I can't promise at the moment. 

(Of course, it's also possible our mystery releaser will pick things up in the background)
