### ISSUE TITLE
Voice instructions: Cancel reading if already at next

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#538]
Sometimes a cycleway might not have a name, so the API creates a name like "Link joining Bradford Road, A650, Station Lane, Along the side of A653, Slip road, A653, ...". Whilst this is not ideal, it is the best that can be achieved given the data.

However, this can take a long time to read. By the time this has finished, the cyclist may already be at the next instruction, but this is then missed because the above is still being read out.

So the fix is to cancel reading of an instruction if the user has already reached the next point.

**Comment by dan424gg** [comment]
I'm working on it!

**Comment by dan424gg** [comment]
I would like to be assigned to this issue as I have a solution.

**Comment by oliverlockwood** [comment]
@dan424gg done. Look forward to your PR.

**Comment by HilaryN** [comment]
Thanks so much for your contribution, @dan424gg .
