### ISSUE TITLE
Can't add photos to photomap any more

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#542]
A user reports:

I tried to add a picture of cycle parking to the photomap today, and wasn't able to! It said that I'd denied permission to access my device storage or camera, when I hadn't. I looked in my app settings, and it didn't look like I could grant the app permission for this either. I'm using a Google Pixel 5.

I tried force-quitting to see if the permission would be requested, and even tried uninstalling and reinstalling the app and had the same issue. Looks like it doesn't recognise that it needs storage/photo permission.

![Screenshot_20231125-191627](https://github.com/cyclestreets/android/assets/361423/e2b7f56c-2b70-4d58-aab2-2bf6b5a4f297)
![Screenshot_20231125-191704](https://github.com/cyclestreets/android/assets/361423/02db15ae-0110-4620-aeb3-50cfa42fc60c)

**Comment by HilaryN** [comment]
Yes, unfortunately I've had the same problem on Android 13 with the map tiles - it will no longer cache them.  WRITE_EXTERNAL_STORAGE, which is the permission we are using for storing photos and map tiles, has been deprecated.  
I'm hoping to sort it but I've been hampered by the fact that I can't do a build on my PC at the moment :-(  I hope to get to it.

**Comment by HilaryN** [comment]
@mvl22 should we allow videos to be uploaded as well, or just photos?

**Comment by mvl22** [comment]
> @mvl22 should we allow videos to be uploaded as well, or just photos?

That would be a useful feature to add and there is partial support at the server side, it is not yet documented or formally supported.

I would treat that as a separate issue, for future consideration.

For now what is most important is ensuring the current photo feature is working.
