### ISSUE TITLE
Incorrect Retrieval of Street Names in Itinerary

### ISSUE THREAD

**Issue by Tharsipa** [cyclestreets/android#551]
### **How to reproduce:**

1. Launch the CycleStreets app.
2. Start a new route and input the starting point and end point.
3. Select a route type (e.g., fastest route, quietest route).
4. Click "Find Route" to generate the route.
5. Navigate to the dashboard.
6. Click on "Itinerary" to view the route directions.
7. In the itinerary, you will encounter directions such as "Turn left" or "Turn right" into segments labelled as "Short un-named link."

### **Actual Behavior:**
<img src="https://github.com/cyclestreets/android/assets/90727247/b78a5465-62ee-4d58-91dd-208c68f0b6dd" width="300">

The itinerary provides directions to turn left or right into segments labeled "Short un-named link," which indicates that the app fails to retrieve or display the proper street names or identifiers for certain route segments. This can confuse users and make navigation challenging.

### **Expected Behaviour:**
The itinerary should accurately retrieve and display the street names or identifiers for all route segments, providing clear and descriptive directions to users. Directions should be presented with identifiable street names to facilitate easy navigation along the route.

**Device Model:** Pixel 7 
**Android Version:** Android 8.1
**App version:** net.cyclestreets/3.10.2/1658

### **Duplicate Check**
I have searched the existing issues and confirm that this bug has not been reported before.

**Comment by mvl22** [comment]
> Short un-named link

These are links that don't have names. It is common when cycling that one uses paths that don't have names. This is not a bug.
