### ISSUE TITLE
Update app on F-Droid store

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#556]
Sounds like the release is out of date - could we get it there too?

https://fediscience.org/@ericsfraga/112581133808066830

Looks like the latest edition is:
Version 3.7.2 (1579) suggested Added on May 15, 2020

https://f-droid.org/en/packages/net.cyclestreets/

so yes, we really do need to get this updated. No wonder it is crashing on newer Android.

**Comment by mvl22** [comment]
Previously done at:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6712

**Comment by jezhiggins** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15216

**Comment by mvl22** [comment]
Excellent, thanks Jez.

In the future, could we do this on a branch in the cyclestreets/android repo, so that it's clear that this is an official submission, that users can therefore be assured trust for?

PS Is there any way to automate this? Would be good to get this in a submission pipeline if possible, so that non-Google users can get regular releases.

**Comment by mvl22** [comment]
Do we know when this will appear on their site?

**Comment by jezhiggins** [comment]
> Excellent, thanks Jez.
> 
> In the future, could we do this on a branch in the cyclestreets/android repo, so that it's clear that this is an official submission, that users can therefore be assured trust for?
> 
> PS Is there any way to automate this? Would be good to get this in a submission pipeline if possible, so that non-Google users can get regular releases.

Not sure about automation, but I think there are things we can do to make it a little bit easier.

Wrt to where the PR comes from, I don't think that's visible to the end user. You could find it if you dug around in the fdroid code, but in the FDroid store it's not something they show. In any event, their builds  always come from "official" repositories. They don't snapshot the code they build, they pull it from the original repository each time, so when they build the CycleStreets app they're pulling the code from our repository.

**Comment by jezhiggins** [comment]
> Do we know when this will appear on their site?

They don't give ETAs, but reading around suggests typically within 4 days

**Comment by jezhiggins** [comment]
Live now

**Comment by mvl22** [comment]
Great, thanks!

@smsm1 could you let the original reporter know?
