### ISSUE TITLE
Conversion of three-message UI for waypoints to two

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#65]
The mobile site at http://m.cyclestreets.net/ has achieved having only two UI elements rather than three for stage 3 (potentially setting waypoints). This is done by making a move by the user (rather than clicking to plan) as indicative that the user wants to add waypoints.

We should assess in a week or two whether users are finding this OK, and if so, move to using two rather than three elements.

**Comment by oliverlockwood** [comment]
@mvl22 I'm not sure I understand this issue as it stands.  Could you please clarify, or close it?

**Comment by mvl22** [comment]
This is all obsoleted by the new UI in the design which is intended to avoid all kinds of observed UI failures in the current UIs across the various platforms.
