### ISSUE TITLE
'Route number' is not clear

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#73]
A user giving feedback has commented that it is not clear what the route number box, where a 'CycleStreets route' can be entered, is for.

We should add some brief explanatory text that this refers to the number of a route planned on the www.cyclestreets.net website (as distinct from any on-street route signage number).

**Comment by oliverlockwood** [comment]
@mvl22 there's currently a grey text hint "Route number" in the box, see the screenshot:
<img src="https://user-images.githubusercontent.com/6017680/42878840-67e822ec-8a86-11e8-98bf-fc65ae4fd48d.png" width="270" height="480">

Would it be sufficient to change this text to be "CycleStreets route number"?  Or would you prefer a more verbose subtitle?  This should be a fairly simple change if we work out how we want to display it.  (The currently proposed InVision UI designs don't show this screen.)

**Comment by mvl22** [comment]
> CycleStreets route number

Yes, that would be much clearer.

Also I think "Find route" should be "Load route" - find implies a search, e.g. for a National Cycle Network route.

You could add explanatory text, such as:

"If you have planned a route on the CycleStreets website, you can load it here, by entering the route number shown on the webpage."

**Comment by oliverlockwood** [comment]
@mvl22 Ok on the first two points.

Regarding the explanatory text,  that seems too specific; there are other cases, for example someone could be typing in a route number their friend had planned (I was doing this at the weekend!)

Do you want to propose a broader description or would you rather I had a go?

**Comment by mvl22** [comment]
Feel free to add some text that makes sense.

I suspect though that people will realise that "you have planned" means "a route that has been planned".

**Comment by oliverlockwood** [comment]
I more meant that it wouldn't had to have been planned on the CycleStreets website; it could have been planned through an app (whether android or otherwise).

Will put together a PR shortly.

**Comment by mvl22** [comment]
Routes planned with one API key aren't usually visible on another. The main exception is the website.

**Comment by oliverlockwood** [comment]
Here's my proposal:
<img width="271" alt="screen shot 2018-07-18 at 18 40 01" src="https://user-images.githubusercontent.com/6017680/42898145-3b6f0328-8aba-11e8-94ac-e5ebc47cb408.png">

(although I decided to remove the trailing full stop that this screenshot shows).

What do you think?

Implementation is in #229.

**Comment by mvl22** [comment]
Looks great :)

**Comment by jf1** [comment]
> Routes planned with one API key aren't usually visible on another. The main exception is the website.

@mvl22 for the avoidance of doubt, please can you clarify that all CycleStreets routes can be viewed using any CycleStreets app/interface?

**Comment by mvl22** [comment]
> @mvl22 for the avoidance of doubt, please can you clarify that all CycleStreets routes can be viewed
> using any CycleStreets app/interface?

That is indeed the intent, that CycleStreets interfaces are interchangeably treated as one product. Let me know if you find cases where this isn't the case. I've just tested website -> iPhone and that indeed works.
