### ISSUE TITLE
Don't include jar libraries, define them as gradle deps

### ISSUE THREAD

**Issue by mvdan** [cyclestreets/android#84]
It is both impractical and expensive to keep jars in the source code. It would be a lot easier to define the package names and versions as dependencies in build.gradle, like it is suggested in the Android manual.

**Comment by Rudloff** [comment]
I see this was closed but the repository still contains a jar at `libraries/cyclestreets-view/libs/mapsforge-map-0.3.0-jar-with-dependencies.jar` and the build fails without it:
```
Execution failed for task ':libraries:cyclestreets-view:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

This prevents F-Droid (see #194) from distributing recent versions of this app.

**Comment by Rudloff** [comment]
Unfortunately, mapsforge 0.3.0 is not available in Maven Central.
I tried to update to 0.4.3 like this:
```diff
diff --git a/libraries/cyclestreets-view/build.gradle b/libraries/cyclestreets-view/build.gradle
index 412c64d6..05630941 100644
--- a/libraries/cyclestreets-view/build.gradle
+++ b/libraries/cyclestreets-view/build.gradle
@@ -2,7 +2,7 @@ evaluationDependsOn(':libraries:cyclestreets-core')
 
 dependencies {
   compile project(':libraries:cyclestreets-core')
-  compile files('libs/mapsforge-map-0.3.0-jar-with-dependencies.jar')
+  compile 'org.mapsforge:mapsforge-map-android:0.4.3'
   compile 'com.getpebble:pebblekit:3.1.0@aar'
 
   // In the main app project, we're already pulling in 23.x via the `acra` dependency.
```

But it seems some of the mapsforge classes have changed and I don't know enough about it to fix the cyclestreets code.

**Comment by jezhiggins** [comment]
Progress - https://github.com/jezhiggins/cyclestreets-android/tree/mapsforge-update
It's not quite there yet and also involves changes to the accompanying offline-mappack, but it's nearly there.

**Comment by oliverlockwood** [comment]
Good stuff, by the way @jezhiggins do you want any help to get the map pack building and publishing on Travis, like the app does?

**Comment by mvl22** [comment]
> map pack building and publishing on Travis, like the app does?

Would really like to get the map packs being updated regularly, and to have more of them. We get complaints every so often that they are out of date. Let's discuss that over here -->

https://github.com/cyclestreets/android-mappacks/issues

**Comment by oliverlockwood** [comment]
I believe this can now be considered closed.
