### ISSUE TITLE
Pebble support

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#86]
Request from Facebook posting:

"I'd love to see it send directions to my Pebble :-)"

**Comment by mvl22** [comment]
https://twitter.com/Looseend/status/569555724507979776

"Seem to have got the basics of Cyclestreets/Pebble integration going. Watch App needs some polish."

**Comment by jezhiggins** [comment]
Jon provided Pebble integration a while back, and it's been part of the build since then.  Not sure of the current status of Pebble watches - think they might have died.  I guess Android Wear is where we look in the future.
