### ISSUE TITLE
Map tile downloads slow

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/android#90]
Even on a fast wifi connection I do notice that map tile downloads can be slow. It might just be the device I'm using - a 3-year-old small HTC device, but we have had other reports.

In the first instance, could I suggest that we ensure we're running the latest build of osmdroid, as per
https://github.com/osmdroid/osmdroid/commits/master
which does seem to be a very active project.

**Comment by jezhiggins** [comment]
Closing this due to age.  Reopen with a new issue is necessary.
