### ISSUE TITLE
Alert to prevent phone loss if rider gets off bike.

### ISSUE THREAD

**Issue by bdsl** [cyclestreets/android#94]
I thought I had my phone stolen from a handlebar yesterday. In fact I still have it, but I wonder if this could make it harder to lose phones:

During a liveride session, use the accelerometer every ten seconds or so to check that the bike is moving. If it isn't moving then the rider must have got off the bike and could be in danger of losing their phone, so the app could make a loud noise to alert them.

Perhaps this could be implemented within the cyclestreets app, or perhaps it could be a separate app and cyclestreets could offer to start it at the same time as starting liveride.

I'd be interested in implementing this, but although I have some academic experience of Java I haven't done any work with Android so I don't know whether I would be able to do it in a reasonable time frame, or if other people would want to use it. I'm not sure how much impact the accelerometer would have on battery life.

**Comment by oliverlockwood** [comment]
I can't see this as something we're going to work on any time soon.  I'm going to close this; @bdsl or anyone else feel free to re-raise if you'd like to get involved in proposing a detailed solution and/or submitting a PR.
