### ISSUE TITLE
[BikeHelp] Provide information about bike shops in addition to their names

### ISSUE THREAD

**Issue by oliverlockwood** [cyclestreets/android#97]
If you're out and about and have a mechanical (for example), it would useful not only to see the locations of nearby bike shops (as the app currently does) but also to be able to see the address, phone number, website if these are available - for example, you might want to be able to ring them to see if they're open and if so whether they'd be able to replace a broken gear cable / chain / spoke / whatever.

It is my understanding that the V2 POIs API provides this information, so the dev work here would be as follows:
-  design how this would be displayed on the UI
-  pass through the information from the updated POIs API and display in the UI appropriately (when the API is updated, and if the info is available for the given bike shop).

Any comments or pointers on relevant areas of the code are welcomed, I haven't had the time to go digging yet :smiley:

**Comment by oliverlockwood** [comment]
Resurrecting this... @mvl22 My understanding was that the V2 POIs API would expose address and opening-time information (derived from OSM) so that I should be able to gather this information from the JSON response processed in https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/POICategory.java#L105-161, so long as the fields were requested in https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/main/java/net/cyclestreets/api/ApiClient.java#L293.

However, https://www.cyclestreets.net/api/v2/pois.locations/#parametersoptional makes no mention of address or opening-time in the list of `fields`, so it's not clear what the next step should be.  Can you advise?  Are there some hidden fields I am able to use now, or is there still some work to be done to expose this additional info from OSM on your POIs API?

**Comment by mvl22** [comment]
If you include the `osmTags` field that will include for you the raw OSM data as key/value pairs.

The OSM tag concerned is `opening_hours`, so when the mapper has included that, that key should be present.

**Comment by oliverlockwood** [comment]
@mvl22 That would be great, but I don't think this is working as intended. 😞 

Case example: Bicycle Ambulance in Cambridge.

https://api.cyclestreets.net/v2/pois.locations?type=bikeshops&bbox=0.119,52.209,0.120,52.210&limit=20&fields=name,osmTags&key=<redacted>
returns
```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "name": "Bicycle Ambulance",
                "osmTags": null,
                "id": "113267"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.120061,
                    52.209179
                ]
            }
        }
    ]
}
```

Looking at this on OSM, (https://overpass-turbo.eu/) with the query:
```node
  [shop=bicycle]
  ({{bbox}});
out;```

I see instead:
```Node 961582424

Tags:

addr:city=Cambridge
addr:housename=Level A, Park Street car park
addr:postcode=CB5 8AS
addr:street=Park Street
name=Bicycle Ambulance
opening_hours=Tu-Fr 08:30-18:00; Sa 10:00-18:00
shop=bicycle
source=local_knowledge
source:opening_hours=http://bicycleambulance.com
url=http://bicycleambulance.com
Coordinates:

52.2092986 / 0.1195165 (lat/lon)```

<img width="1106" alt="screen shot 2016-05-25 at 15 52 59" src="https://cloud.githubusercontent.com/assets/6017680/15544723/a135b280-2291-11e6-9f21-16dd5b98d9a8.png">

So it seems the info is there in OSM but `osmTags` comes back as `null` in the POIs API.

Thoughts?

**Comment by oliverlockwood** [comment]
@mvl22 P.S. if you agree that there is a bug at the moment, I'm happy to try to help to dig into it if you can point me in the right direction.

**Comment by mvl22** [comment]
Yes, that must be a bug. Will look at this and get fixed ASAP.

**Comment by oliverlockwood** [comment]
Cool.  I will start coding on the assumption of this being fixed, and hope that by the time I'm ready to raise a PR there'll be a fixed API to test against 😄

**Comment by mvl22** [comment]
I've now established that the OSM data is being processed correctly (it is coming into the system and being stored in the database), so the problem seems to be at code level, which I'm now checking.

**Comment by mvl22** [comment]
> So it seems the info is there in OSM but osmTags comes back as null in the POIs API.

This bug is now fixed - it required quite a bit of tracking down. Sorry this took so long to fix.

**Comment by oliverlockwood** [comment]
This feature is now unblocked by the server-side fix.  I'll look into doing some dev on this soon.

**Comment by mvl22** [comment]
Great we got there on this! Thanks :)

**Comment by oliverlockwood** [comment]
Thanks, I was pleased... it's nice to be making some visible changes after confining myself to backend upgrades for a while 😄
